<script lang="ts">
 // Auto Task approval list; keep decision controls gated by the original bill.
 import {onMount} from 'svelte'; import {supabase,resolveStorageUrl} from '$lib/utils/supabase'; import {locale} from '$lib/i18n'; import {currentUser} from '$lib/utils/persistentAuth';
 export let approvalCount=0; export let displayMode:'panel'|'desktop_rows'|'mobile_cards'|'mobile_compact_rows'='panel';
 let approvals:any[]=[],loading=true,error='',busyKey='',notes:Record<string,string>={},expanded:Record<string,boolean>={},confirmItem:any=null,confirmDecision:'approved'|'rejected'|null=null; $: isArabic=$locale==='ar';
 onMount(load);
 async function load(){loading=true;error='';const {data,error:rpcError}=await supabase.rpc('Autotask_list_my_advance_approvals',{p_user_id:$currentUser?.id});approvals=Array.from(new Map((data||[]).map((i:any)=>[`${i.source_table}:${i.source_record_id}`,i])).values());approvalCount=approvals.length;if(rpcError)error=rpcError.message||'Failed to load Auto Task approvals.';loading=false}
 function key(i:any){return `${i.source_table}:${i.source_record_id}`} function hasBill(i:any){return Boolean(i.original_bill_url?.trim())}
 function viewBill(i:any){if(hasBill(i))window.open(resolveStorageUrl(i.original_bill_url),'_blank','noopener,noreferrer')}
 function openConfirm(i:any,d:'approved'|'rejected'){if(!hasBill(i))return;confirmItem=i;confirmDecision=d}
 function closeConfirm(){if(!busyKey){confirmItem=null;confirmDecision=null}}
 async function confirm(){if(!confirmItem||!confirmDecision)return;await decide(confirmItem,confirmDecision);confirmItem=null;confirmDecision=null}
 async function decide(i:any,d:'approved'|'rejected'){if(!hasBill(i))return;busyKey=key(i);error='';const {error:e}=await supabase.rpc('Autotask_decide_advance_approval',{p_actor_user_id:$currentUser?.id,p_source_table:i.source_table,p_source_record_id:i.source_record_id,p_decision:d,p_notes:notes[key(i)]||null});if(e)error=e.message||'This approval may already have been decided.';await load();busyKey=''}
</script>

{#if displayMode==='mobile_compact_rows'}
 {#each approvals as item}<tr class="autotask-mobile-card" class:expanded={expanded[key(item)]}>
  <td>
   <button class="compact-toggle" type="button" aria-expanded={!!expanded[key(item)]} on:click={()=>expanded={...expanded,[key(item)]:!expanded[key(item)]}}>
    <span><strong>{Number(item.amount||0).toLocaleString()} SAR</strong><small>{item.vendor_name||'—'}</small></span>
    <b>{expanded[key(item)]?'−':'+'}</b>
   </button>
   {#if expanded[key(item)]}<div class="compact-details"><p><b>{isArabic?'الفرع':'Branch'}:</b> {item.branch_id||'—'}</p><p><b>{isArabic?'الحالة':'Status'}:</b> {isArabic?'معلق':'Pending'}</p><p><b>{isArabic?'النوع':'Type'}:</b> {isArabic?'دفعة مقدمة':'Advance'}</p>{#if hasBill(item)}<div class="compact-actions"><button class="view-bill" on:click={()=>viewBill(item)}>👁️ {isArabic?'عرض الفاتورة':'View Bill'}</button><button class="approve" disabled={busyKey===key(item)} on:click={()=>openConfirm(item,'approved')}>{isArabic?'موافقة':'Approve'}</button><button class="reject" disabled={busyKey===key(item)} on:click={()=>openConfirm(item,'rejected')}>{isArabic?'رفض':'Reject'}</button></div>{:else}<p class="waiting">{isArabic?'بانتظار رفع الفاتورة الأصلية':'Waiting for original bill'}</p>{/if}</div>{/if}
  </td>
 </tr>{/each}
{:else if displayMode==='desktop_rows'}
 {#each approvals as item}<tr class="autotask-approval-row">
  <td class="req-number">AUTO PAYMENT<br><small>{item.bill_number||'—'}</small></td><td>{item.branch_id||'—'}</td><td>Auto Task System</td><td>{item.vendor_name}</td><td>{isArabic?'موافقة دفعة مقدمة':'Advance payment approval'}</td><td>{Number(item.amount||0).toLocaleString()} SAR</td><td>{isArabic?'دفعة مقدمة':'Advance'}</td><td><span class="status">{isArabic?'معلق':'Pending'}</span></td><td>—</td><td>{item.requested_at?new Date(item.requested_at).toLocaleString(isArabic?'ar-SA':'en-GB',{hour12:true}):'—'}</td>
  <td class="row-actions">{#if hasBill(item)}<button class="btn-view" title={isArabic?'عرض الفاتورة الأصلية':'View original bill'} on:click={()=>viewBill(item)}>👁️</button><button class="btn-approve-inline" title={isArabic?'موافقة':'Approve'} disabled={busyKey===key(item)} on:click={()=>openConfirm(item,'approved')}>✅</button><button class="btn-reject-inline" title={isArabic?'رفض':'Reject'} disabled={busyKey===key(item)} on:click={()=>openConfirm(item,'rejected')}>❌</button>{:else}<span class="waiting">{isArabic?'بانتظار الفاتورة الأصلية':'Waiting for original bill'}</span>{/if}</td>
 </tr>{/each}
{:else if displayMode==='mobile_cards'}
 {#each approvals as item}<div class="card"><div class="card-head"><strong>{isArabic?'موافقة دفعة مقدمة':'Advance Payment Approval'}</strong><span>{isArabic?'معلق':'Pending'}</span></div><p><b>{isArabic?'المورد':'Vendor'}:</b> {item.vendor_name}</p><p><b>{isArabic?'الفاتورة':'Bill'}:</b> {item.bill_number||'—'}</p><p><b>{isArabic?'المبلغ':'Amount'}:</b> {Number(item.amount||0).toLocaleString()} SAR</p>{#if hasBill(item)}<button class="view-bill" on:click={()=>viewBill(item)}>👁️ {isArabic?'عرض الفاتورة الأصلية':'View Original Bill'}</button><textarea bind:value={notes[key(item)]} placeholder={isArabic?'ملاحظات اختيارية':'Optional notes'}></textarea><div class="actions"><button class="approve" on:click={()=>decide(item,'approved')}>{isArabic?'موافقة':'Approve'}</button><button class="reject" on:click={()=>decide(item,'rejected')}>{isArabic?'رفض':'Reject'}</button></div>{:else}<p class="waiting">{isArabic?'بانتظار رفع الفاتورة الأصلية':'Waiting for original bill upload'}</p>{/if}</div>{/each}
{:else}<section class="panel"><div class="heading"><h2>{isArabic?'موافقات مهام الاستلام التلقائية':'Auto Task Receiving Approvals'}</h2><button on:click={load}>{isArabic?'تحديث':'Refresh'}</button></div>{#if error}<p class="error">{error}</p>{/if}{#if loading}<p>Loading…</p>{:else if !approvals.length}<p>No pending Auto Task approvals.</p>{:else}<div class="cards">{#each approvals as item}<article><h3>{item.vendor_name}</h3><p>Bill: {item.bill_number||'—'}</p><p>Amount: {Number(item.amount||0).toLocaleString()} SAR</p>{#if hasBill(item)}<button class="view-bill" on:click={()=>viewBill(item)}>👁️ View Original Bill</button><textarea bind:value={notes[key(item)]} placeholder="Optional notes"></textarea><div class="actions"><button class="approve" on:click={()=>decide(item,'approved')}>Approve</button><button class="reject" on:click={()=>decide(item,'rejected')}>Reject</button></div>{:else}<p class="waiting">Waiting for original bill upload</p>{/if}</article>{/each}</div>{/if}</section>{/if}

{#if confirmItem&&confirmDecision}<div class="backdrop" role="presentation" on:click={closeConfirm}><div class="dialog" role="dialog" aria-modal="true" on:click|stopPropagation><h3>{confirmDecision==='approved'?(isArabic?'تأكيد الموافقة':'Confirm Approval'):(isArabic?'تأكيد الرفض':'Confirm Rejection')}</h3><p><strong>{confirmItem.vendor_name}</strong></p><p>Bill: {confirmItem.bill_number||'—'} · {Number(confirmItem.amount||0).toLocaleString()} SAR</p><label>{isArabic?'ملاحظات اختيارية':'Optional notes'}</label><textarea bind:value={notes[key(confirmItem)]}></textarea><div class="confirm-actions"><button class="cancel" on:click={closeConfirm}>Cancel</button><button class:approve={confirmDecision==='approved'} class:reject={confirmDecision==='rejected'} disabled={!!busyKey} on:click={confirm}>{busyKey?'Processing…':confirmDecision==='approved'?'Approve':'Reject'}</button></div></div></div>{/if}

<style>
 .panel{margin:1rem 0;padding:1rem;border:1px solid #cbd5e1;border-radius:12px;background:#f8fafc}.heading,.card-head,.actions,.confirm-actions{display:flex;justify-content:space-between;gap:.5rem}.heading h2,h3{margin:0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:.75rem}article,.card{background:#fff;border:1px solid #e2e8f0;border-radius:9px;padding:.8rem;margin-bottom:.65rem}p{font-size:.82rem}textarea{box-sizing:border-box;width:100%;min-height:60px;margin:.55rem 0;border:1px solid #cbd5e1;border-radius:7px;padding:.5rem}.actions button{flex:1;border:0;border-radius:7px;padding:.5rem;color:#fff}.approve{background:#10b981}.reject{background:#dc2626}.error{color:#b91c1c}.autotask-approval-row td{padding:.65rem .75rem;border-bottom:1px solid #e2e8f0;font-size:.75rem}.status{padding:.25rem .55rem;border-radius:999px;background:#fef3c7;color:#92400e;font-weight:700}.row-actions{display:flex;align-items:center;justify-content:center;gap:.5rem}.icon{box-sizing:border-box;width:34px;height:31px;padding:0;border-radius:8px;border:0;display:inline-flex;align-items:center;justify-content:center;cursor:pointer}.icon.view,.view-bill{background:#3b82f6;color:#fff}.icon.reject{width:37px;background:#fff;color:#ef4444;border:1.5px solid #ef4444}.waiting{color:#b45309;font-size:.72rem;font-weight:700}.view-bill{width:100%;margin-top:.55rem;border:0;border-radius:7px;padding:.5rem;font-weight:700}.backdrop{position:fixed;inset:0;z-index:10000;display:flex;align-items:center;justify-content:center;padding:1rem;background:#0f172a80}.dialog{width:min(440px,100%);padding:1.1rem;border-radius:14px;background:#fff}.confirm-actions{justify-content:flex-end}.confirm-actions button{min-width:100px;border:0;border-radius:8px;padding:.6rem .9rem;color:#fff}.cancel{background:#64748b}
 .autotask-mobile-card{display:block;margin:0 0 .55rem;border:1px solid #dbe3ee;border-radius:11px;background:#fff;overflow:hidden;box-shadow:0 2px 7px #0f172a12}.autotask-mobile-card td{display:block;padding:0}.compact-toggle{display:flex;width:100%;min-height:58px;align-items:center;justify-content:space-between;gap:.6rem;padding:.65rem .8rem;border:0;background:#fff;text-align:start;color:#1e293b}.compact-toggle span{display:flex;min-width:0;flex-direction:column;gap:.18rem}.compact-toggle strong{font-size:.84rem}.compact-toggle small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#64748b}.compact-toggle b{display:grid;width:34px;height:34px;flex:0 0 34px;place-items:center;border-radius:50%;background:#eff6ff;color:#2563eb;font-size:1.25rem}.compact-details{padding:.1rem .8rem .75rem;border-top:1px solid #e5e7eb}.compact-details p{margin:.5rem 0}.compact-actions{display:grid;grid-template-columns:1fr 1fr;gap:.45rem}.compact-actions button{min-height:44px;border:0;border-radius:8px;color:#fff}.compact-actions .view-bill{grid-column:1/-1;margin:0}.compact-actions .approve{background:#10b981}.compact-actions .reject{background:#dc2626}
</style>
