import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { databaseClient, requireBreakUser } from '$lib/server/breakRegisterAuth';

async function master(cookies:any){ const user=await requireBreakUser(cookies,'desktop'); const db=databaseClient(); const {data}=await db.from('users').select('is_master_admin').eq('id',user.id).single(); if(!data?.is_master_admin) throw new Error('FORBIDDEN'); return {db,user}; }

export const GET: RequestHandler = async ({cookies}) => { try { const {db}=await master(cookies); const {data:users,error}=await db.from('user_management_view').select('id,username,employee_name,branch_name,status,is_master_admin').eq('status','active').order('username'); if(error) throw error; const {data:access}=await db.from('aqura_voice_access').select('*'); const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()); const {data:usage}=await db.from('aqura_voice_daily_usage').select('user_id,usage_count').eq('usage_date',today); return json({success:true,users:(users||[]).map((u:any)=>({...u,aqura_voice:(access||[]).find((a:any)=>a.user_id===u.id)||null,used_today:(usage||[]).find((x:any)=>x.user_id===u.id)?.usage_count||0}))}); } catch(e:any){ return json({success:false,error:e.message==='FORBIDDEN'?'Master Admin access required':'Failed to load Aqura Voice controls'},{status:e.message==='FORBIDDEN'?403:500}); } };

export const POST: RequestHandler = async ({cookies,request}) => { try { const {db,user}=await master(cookies); const body=await request.json(); if(!body.userId) return json({success:false,error:'User is required'},{status:400}); const dailyLimit=Math.max(1,Math.min(10000,Number(body.dailyLimit)||10)); const {error}=await db.from('aqura_voice_access').upsert({user_id:body.userId,is_enabled:body.isEnabled===true,daily_limit:dailyLimit,subscription_expiry:body.subscriptionExpiry||null,granted_by:user.id,updated_at:new Date().toISOString()},{onConflict:'user_id'}); if(error) throw error; return json({success:true}); } catch(e:any){ return json({success:false,error:e.message==='FORBIDDEN'?'Master Admin access required':e.message},{status:e.message==='FORBIDDEN'?403:500}); } };
