-- SAFE UNIVERSAL RLS POLICY (No Deadlock)
-- This version is slower but safer - enables RLS one table at a time

-- Step 1: Enable RLS on all tables (one at a time to avoid deadlocks)
ALTER TABLE app_functions ENABLE ROW LEVEL SECURITY;
ALTER TABLE approval_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE biometric_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE bogo_offer_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupon_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupon_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupon_eligible_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupon_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_access_code_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_app_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_recovery_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE deleted_bundle_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_fee_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_service_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_fine_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_warning_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_warnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE erp_daily_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_parent_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_requisitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_scheduler ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_sub_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE flyer_offer_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE flyer_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE flyer_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE flyer_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_employee_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_employee_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_fingerprint_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_position_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_position_reporting_template ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_salary_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE hr_salary_wages ENABLE ROW LEVEL SECURITY;
ALTER TABLE interface_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE non_approved_payment_scheduler ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_read_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_recipients ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE offer_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE offer_cart_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE offer_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE offer_usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quick_task_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE quick_task_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE quick_task_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quick_task_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE quick_task_user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE quick_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE receiving_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE receiving_task_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE receiving_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE recurring_assignment_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE recurring_schedule_check_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE requesters ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE shelf_paper_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_reminder_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tax_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_device_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_password_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE variation_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_payment_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;

-- Verify
SELECT 
  COUNT(*) as total_tables,
  SUM(CASE WHEN rowsecurity THEN 1 ELSE 0 END) as rls_enabled_count
FROM pg_tables 
WHERE schemaname = 'public';
