begin;

create table if not exists public.company_document_types (
  id bigint generated by default as identity primary key,
  name_ar text not null check (length(trim(name_ar)) > 0),
  name_en text not null check (length(trim(name_en)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists company_document_types_name_ar_unique
  on public.company_document_types (lower(trim(name_ar)));

create unique index if not exists company_document_types_name_en_unique
  on public.company_document_types (lower(trim(name_en)));

alter table public.company_document_types enable row level security;

drop policy if exists authenticated_read on public.company_document_types;
create policy authenticated_read
  on public.company_document_types for select to authenticated
  using (true);

grant select on public.company_document_types to authenticated;
revoke insert, update, delete on public.company_document_types from authenticated;
revoke all on sequence public.company_document_types_id_seq from authenticated;

create or replace function public.create_company_document_type(p_name_ar text, p_name_en text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if auth.uid() is null or not exists (
    select 1 from public.users where id = public.aqura_current_user_id()
  ) then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(p_name_ar), '') is null or nullif(trim(p_name_en), '') is null then
    raise exception 'Arabic and English document names are required';
  end if;

  insert into public.company_document_types (name_ar, name_en)
  values (trim(p_name_ar), trim(p_name_en))
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.create_company_document_type(text, text) from public, anon;
grant execute on function public.create_company_document_type(text, text) to authenticated, service_role;

commit;
