begin;

create table if not exists public.company_documents (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.company_master(id),
  branch_id bigint references public.branches(id),
  custom_document_type_id bigint references public.company_document_types(id),
  document_type_key text not null,
  document_name_ar text not null,
  document_name_en text not null,
  document_scope text not null check (document_scope in ('common', 'branch_wise')),
  document_number text,
  expiry_date date,
  storage_bucket text,
  storage_path text,
  original_file_name text,
  file_mime_type text,
  file_size bigint,
  notification_emails text[] not null default '{}',
  notification_whatsapp_numbers text[] not null default '{}',
  notification_period_days integer[] not null default '{}',
  reminder_time time without time zone,
  created_by uuid default public.aqura_current_user_id(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((document_scope = 'common' and branch_id is null) or (document_scope = 'branch_wise' and branch_id is not null)),
  check ((storage_bucket is null and storage_path is null) or (storage_bucket is not null and storage_path is not null))
);

create index if not exists company_documents_company_idx on public.company_documents(company_id);
create index if not exists company_documents_branch_idx on public.company_documents(branch_id);
create index if not exists company_documents_expiry_idx on public.company_documents(expiry_date);

alter table public.company_documents enable row level security;
drop policy if exists authenticated_read_company_documents on public.company_documents;
create policy authenticated_read_company_documents on public.company_documents
  for select to authenticated using (true);
grant select on public.company_documents to authenticated;
revoke insert, update, delete on public.company_documents from authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('company-documents', 'company-documents', false, 20971520, array['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists company_documents_authenticated_insert on storage.objects;
create policy company_documents_authenticated_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'company-documents');

drop policy if exists company_documents_authenticated_select on storage.objects;
create policy company_documents_authenticated_select on storage.objects
  for select to authenticated
  using (bucket_id = 'company-documents');

drop policy if exists company_documents_authenticated_delete on storage.objects;
create policy company_documents_authenticated_delete on storage.objects
  as restrictive for delete to authenticated
  using (
    bucket_id <> 'company-documents'
    or exists (
      select 1 from public.users
      where id = public.aqura_current_user_id() and is_master_admin = true
    )
  );

create or replace function public.save_company_document(
  p_company_id bigint,
  p_branch_id bigint,
  p_custom_document_type_id bigint,
  p_document_type_key text,
  p_document_name_ar text,
  p_document_name_en text,
  p_document_scope text,
  p_document_number text,
  p_expiry_date date,
  p_storage_bucket text,
  p_storage_path text,
  p_original_file_name text,
  p_file_mime_type text,
  p_file_size bigint,
  p_notification_emails text[],
  p_notification_whatsapp_numbers text[],
  p_notification_period_days integer[],
  p_reminder_time time without time zone
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_id bigint;
begin
  if auth.uid() is null or not exists (
    select 1 from public.users where id = public.aqura_current_user_id()
  ) then raise exception 'Authentication required'; end if;

  if p_document_scope not in ('common', 'branch_wise') then raise exception 'Invalid document scope'; end if;
  if p_document_scope = 'branch_wise' and p_branch_id is null then raise exception 'Branch is required'; end if;
  if p_document_scope = 'common' then p_branch_id := null; end if;
  if p_branch_id is not null and not exists (
    select 1 from public.branches where id = p_branch_id and company_id = p_company_id and is_active = true
  ) then raise exception 'The selected active branch does not belong to this company'; end if;

  insert into public.company_documents (
    company_id, branch_id, custom_document_type_id, document_type_key,
    document_name_ar, document_name_en, document_scope, document_number, expiry_date,
    storage_bucket, storage_path, original_file_name, file_mime_type, file_size,
    notification_emails, notification_whatsapp_numbers, notification_period_days, reminder_time
  ) values (
    p_company_id, p_branch_id, p_custom_document_type_id, trim(p_document_type_key),
    trim(p_document_name_ar), trim(p_document_name_en), p_document_scope, nullif(trim(p_document_number), ''), p_expiry_date,
    nullif(trim(p_storage_bucket), ''), nullif(trim(p_storage_path), ''), nullif(trim(p_original_file_name), ''), nullif(trim(p_file_mime_type), ''), p_file_size,
    coalesce(p_notification_emails, '{}'), coalesce(p_notification_whatsapp_numbers, '{}'), coalesce(p_notification_period_days, '{}'), p_reminder_time
  ) returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.save_company_document(bigint, bigint, bigint, text, text, text, text, text, date, text, text, text, text, bigint, text[], text[], integer[], time without time zone) from public, anon;
grant execute on function public.save_company_document(bigint, bigint, bigint, text, text, text, text, text, date, text, text, text, text, bigint, text[], text[], integer[], time without time zone) to authenticated, service_role;

create or replace function public.update_company_document(
  p_document_id bigint,
  p_company_id bigint,
  p_branch_id bigint,
  p_custom_document_type_id bigint,
  p_document_type_key text,
  p_document_name_ar text,
  p_document_name_en text,
  p_document_scope text,
  p_document_number text,
  p_expiry_date date,
  p_storage_bucket text,
  p_storage_path text,
  p_original_file_name text,
  p_file_mime_type text,
  p_file_size bigint,
  p_notification_emails text[],
  p_notification_whatsapp_numbers text[],
  p_notification_period_days integer[],
  p_reminder_time time without time zone
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not exists (
    select 1 from public.users where id = public.aqura_current_user_id()
  ) then raise exception 'Authentication required'; end if;

  if p_document_scope not in ('common', 'branch_wise') then raise exception 'Invalid document scope'; end if;
  if p_document_scope = 'branch_wise' and p_branch_id is null then raise exception 'Branch is required'; end if;
  if p_document_scope = 'common' then p_branch_id := null; end if;
  if p_branch_id is not null and not exists (
    select 1 from public.branches where id = p_branch_id and company_id = p_company_id and is_active = true
  ) then raise exception 'The selected active branch does not belong to this company'; end if;

  update public.company_documents set
    company_id = p_company_id,
    branch_id = p_branch_id,
    custom_document_type_id = p_custom_document_type_id,
    document_type_key = trim(p_document_type_key),
    document_name_ar = trim(p_document_name_ar),
    document_name_en = trim(p_document_name_en),
    document_scope = p_document_scope,
    document_number = nullif(trim(p_document_number), ''),
    expiry_date = p_expiry_date,
    storage_bucket = nullif(trim(p_storage_bucket), ''),
    storage_path = nullif(trim(p_storage_path), ''),
    original_file_name = nullif(trim(p_original_file_name), ''),
    file_mime_type = nullif(trim(p_file_mime_type), ''),
    file_size = p_file_size,
    notification_emails = coalesce(p_notification_emails, '{}'),
    notification_whatsapp_numbers = coalesce(p_notification_whatsapp_numbers, '{}'),
    notification_period_days = coalesce(p_notification_period_days, '{}'),
    reminder_time = p_reminder_time,
    updated_at = now()
  where id = p_document_id;

  if not found then raise exception 'Document not found'; end if;
end;
$$;

revoke all on function public.update_company_document(bigint, bigint, bigint, bigint, text, text, text, text, text, date, text, text, text, text, bigint, text[], text[], integer[], time without time zone) from public, anon;
grant execute on function public.update_company_document(bigint, bigint, bigint, bigint, text, text, text, text, text, date, text, text, text, text, bigint, text[], text[], integer[], time without time zone) to authenticated, service_role;

create or replace function public.delete_company_document(p_document_id bigint)
returns table(storage_bucket text, storage_path text)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not exists (
    select 1 from public.users
    where id = public.aqura_current_user_id() and is_master_admin = true
  ) then raise exception 'Master admin access required'; end if;

  return query
  delete from public.company_documents d
  where d.id = p_document_id
  returning d.storage_bucket, d.storage_path;

  if not found then raise exception 'Document not found'; end if;
end;
$$;

revoke all on function public.delete_company_document(bigint) from public, anon;
grant execute on function public.delete_company_document(bigint) to authenticated, service_role;

notify pgrst, 'reload schema';
commit;
