BEGIN;

ALTER TABLE public.branches
  ADD COLUMN IF NOT EXISTS biometric_edge_sync_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS biometric_edge_sync_enabled_at timestamptz,
  ADD COLUMN IF NOT EXISTS biometric_edge_sync_enabled_by uuid;

CREATE TABLE IF NOT EXISTS public.biometric_sync_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id bigint REFERENCES public.branches(id),
  branch_name text,
  sync_type text NOT NULL CHECK (sync_type IN ('punches','employees','both','dry-run')),
  trigger_type text NOT NULL CHECK (trigger_type IN ('scheduled','manual','test')),
  triggered_by uuid,
  status text NOT NULL CHECK (status IN ('running','success','failed','skipped')),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  window_from timestamptz,
  window_to timestamptz,
  records_fetched integer NOT NULL DEFAULT 0,
  records_inserted integer NOT NULL DEFAULT 0,
  records_updated integer NOT NULL DEFAULT 0,
  records_skipped integer NOT NULL DEFAULT 0,
  duplicates_filtered integer NOT NULL DEFAULT 0,
  error_code text,
  error_message text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS biometric_sync_logs_branch_created_idx
  ON public.biometric_sync_logs(branch_id, created_at DESC);
CREATE INDEX IF NOT EXISTS biometric_sync_logs_status_created_idx
  ON public.biometric_sync_logs(status, created_at DESC);

ALTER TABLE public.biometric_sync_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS biometric_sync_logs_authenticated_read ON public.biometric_sync_logs;
CREATE POLICY biometric_sync_logs_authenticated_read ON public.biometric_sync_logs
  FOR SELECT TO authenticated USING (true);
GRANT SELECT ON public.biometric_sync_logs TO authenticated;
GRANT ALL ON public.biometric_sync_logs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.biometric_sync_logs_id_seq TO service_role;

CREATE TABLE IF NOT EXISTS public.biometric_sync_locks (
  branch_id bigint PRIMARY KEY REFERENCES public.branches(id) ON DELETE CASCADE,
  run_id uuid NOT NULL,
  locked_until timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.biometric_sync_locks ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.biometric_sync_locks TO service_role;

CREATE OR REPLACE FUNCTION public.get_biometric_sync_branch_status()
RETURNS TABLE (
  branch_id bigint,
  branch_name text,
  branch_active boolean,
  sync_enabled boolean,
  enabled_at timestamptz,
  ready boolean,
  missing_requirements text[],
  last_sync_at timestamptz,
  last_employee_sync_at timestamptz,
  last_log_status text,
  last_log_at timestamptz
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT b.id,
         b.name_en,
         b.is_active,
         b.biometric_edge_sync_enabled,
         b.biometric_edge_sync_enabled_at,
         cardinality(ARRAY_REMOVE(ARRAY[
           CASE WHEN NOT b.is_active THEN 'Branch is inactive' END,
           CASE WHEN ec.branch_id IS NULL THEN 'Active ERP connection is missing' END,
           CASE WHEN NULLIF(trim(ec.tunnel_url), '') IS NULL THEN 'Cloudflare tunnel URL is missing' END,
           CASE WHEN NULLIF(trim(ec.bridge_api_secret), '') IS NULL THEN 'Bridge API secret is missing' END,
           CASE WHEN bc.branch_id IS NULL THEN 'Active biometric connection is missing' END,
           CASE WHEN NULLIF(trim(bc.branch_location_code), '') IS NULL THEN 'Branch location code is missing' END
         ], NULL)) = 0,
         ARRAY_REMOVE(ARRAY[
           CASE WHEN NOT b.is_active THEN 'Branch is inactive' END,
           CASE WHEN ec.branch_id IS NULL THEN 'Active ERP connection is missing' END,
           CASE WHEN NULLIF(trim(ec.tunnel_url), '') IS NULL THEN 'Cloudflare tunnel URL is missing' END,
           CASE WHEN NULLIF(trim(ec.bridge_api_secret), '') IS NULL THEN 'Bridge API secret is missing' END,
           CASE WHEN bc.branch_id IS NULL THEN 'Active biometric connection is missing' END,
           CASE WHEN NULLIF(trim(bc.branch_location_code), '') IS NULL THEN 'Branch location code is missing' END
         ], NULL),
         bc.last_sync_at,
         bc.last_employee_sync_at,
         ll.status,
         ll.created_at
  FROM public.branches b
  LEFT JOIN LATERAL (
    SELECT e.branch_id, e.tunnel_url, e.bridge_api_secret
    FROM public.erp_connections e WHERE e.branch_id = b.id AND e.is_active = true LIMIT 1
  ) ec ON true
  LEFT JOIN LATERAL (
    SELECT c.branch_id, c.branch_location_code, c.last_sync_at, c.last_employee_sync_at
    FROM public.biometric_connections c WHERE c.branch_id = b.id AND c.is_active = true LIMIT 1
  ) bc ON true
  LEFT JOIN LATERAL (
    SELECT l.status, l.created_at FROM public.biometric_sync_logs l
    WHERE l.branch_id = b.id ORDER BY l.created_at DESC LIMIT 1
  ) ll ON true
  ORDER BY b.id;
$$;
REVOKE ALL ON FUNCTION public.get_biometric_sync_branch_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_biometric_sync_branch_status() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_biometric_sync_branch_status() TO service_role;

CREATE OR REPLACE FUNCTION public.set_biometric_edge_sync_enabled(p_branch_id bigint, p_enabled boolean)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_missing text[]; v_ready boolean;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  SELECT s.ready, s.missing_requirements INTO v_ready, v_missing
  FROM public.get_biometric_sync_branch_status() s WHERE s.branch_id = p_branch_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Branch not found'; END IF;
  IF p_enabled AND NOT v_ready THEN
    RETURN jsonb_build_object('success', false, 'missing', v_missing);
  END IF;
  UPDATE public.branches SET
    biometric_edge_sync_enabled = p_enabled,
    biometric_edge_sync_enabled_at = CASE WHEN p_enabled THEN now() ELSE NULL END,
    biometric_edge_sync_enabled_by = CASE WHEN p_enabled THEN auth.uid() ELSE NULL END
  WHERE id = p_branch_id;
  RETURN jsonb_build_object('success', true, 'enabled', p_enabled);
END;
$$;
REVOKE ALL ON FUNCTION public.set_biometric_edge_sync_enabled(bigint, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_biometric_edge_sync_enabled(bigint, boolean) TO authenticated;

CREATE OR REPLACE FUNCTION public.acquire_biometric_sync_lock(p_branch_id bigint, p_run_id uuid, p_seconds integer DEFAULT 240)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.biometric_sync_locks(branch_id, run_id, locked_until, updated_at)
  VALUES (p_branch_id, p_run_id, now() + make_interval(secs => greatest(30, least(p_seconds, 900))), now())
  ON CONFLICT (branch_id) DO UPDATE SET run_id=excluded.run_id, locked_until=excluded.locked_until, updated_at=now()
  WHERE biometric_sync_locks.locked_until < now();
  RETURN FOUND;
END; $$;

CREATE OR REPLACE FUNCTION public.release_biometric_sync_lock(p_branch_id bigint, p_run_id uuid)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  DELETE FROM public.biometric_sync_locks WHERE branch_id=p_branch_id AND run_id=p_run_id;
$$;
REVOKE ALL ON FUNCTION public.acquire_biometric_sync_lock(bigint, uuid, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.release_biometric_sync_lock(bigint, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.acquire_biometric_sync_lock(bigint, uuid, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_biometric_sync_lock(bigint, uuid) TO service_role;

COMMIT;
