begin;

create table if not exists public.hr_analysed_break_data (
  id bigint generated by default as identity primary key,
  break_id uuid not null references public.break_register(id) on delete cascade,
  user_id uuid not null,
  employee_id varchar(50) not null,
  employee_name_en varchar(200),
  employee_name_ar varchar(200),
  branch_id integer,
  reason_id integer,
  reason_note text,
  start_time timestamptz not null,
  end_time timestamptz,
  duration_seconds integer,
  status varchar(20) not null,
  shift_date date not null,
  shift_source text not null default 'unmatched',
  shift_version_id bigint,
  shift_slot_order integer,
  shift_start_time time,
  shift_end_time time,
  shift_end_buffer numeric,
  is_overnight boolean not null default false,
  is_scheduled boolean not null default false,
  schedule_exception text,
  analysis_version integer not null default 1,
  analyzed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint hr_analysed_break_data_break_id_key unique (break_id),
  constraint hr_analysed_break_data_status_check check (status in ('open', 'closed')),
  constraint hr_analysed_break_data_duration_check check (duration_seconds is null or duration_seconds >= 0)
);

create index if not exists idx_analysed_break_employee_shift_date
  on public.hr_analysed_break_data(employee_id, shift_date);
create index if not exists idx_analysed_break_user_shift_date
  on public.hr_analysed_break_data(user_id, shift_date);
create index if not exists idx_analysed_break_branch_shift_date
  on public.hr_analysed_break_data(branch_id, shift_date);
create index if not exists idx_analysed_break_status
  on public.hr_analysed_break_data(status);

alter table public.hr_analysed_break_data enable row level security;

comment on table public.hr_analysed_break_data is
  'Rebuildable reporting projection of break_register. Written only by analyze-breaks; break_register remains the raw ledger.';
comment on column public.hr_analysed_break_data.shift_date is
  'Canonical Saudi business shift date assigned by analyze-breaks.';

commit;
