begin;

create table if not exists public.company_master (
  id bigint generated by default as identity primary key,
  name_ar text not null check (length(trim(name_ar)) > 0),
  name_en text not null check (length(trim(name_en)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists company_master_name_ar_unique
  on public.company_master (lower(trim(name_ar)));

create unique index if not exists company_master_name_en_unique
  on public.company_master (lower(trim(name_en)));

alter table public.company_master enable row level security;

drop policy if exists authenticated_read on public.company_master;
create policy authenticated_read
  on public.company_master for select to authenticated
  using (true);

grant select on public.company_master to authenticated;
revoke insert, update, delete on public.company_master from authenticated;
revoke all on sequence public.company_master_id_seq from authenticated;

create or replace function public.create_company(p_name_ar text, p_name_en text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if auth.uid() is null or not exists (
    select 1 from public.users where id = public.aqura_current_user_id()
  ) then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(p_name_ar), '') is null or nullif(trim(p_name_en), '') is null then
    raise exception 'Arabic and English names are required';
  end if;

  insert into public.company_master (name_ar, name_en)
  values (trim(p_name_ar), trim(p_name_en))
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.create_company(text, text) from public, anon;
grant execute on function public.create_company(text, text) to authenticated, service_role;

commit;
