<script>
	import { createEventDispatcher, onMount } from 'svelte';
	import { get } from 'svelte/store';
	import { supabase } from '$lib/utils/supabase';
	import { currentUser, isAuthenticated } from '$lib/utils/persistentAuth';
	import { notificationManagement } from '$lib/utils/notificationManagement';
	import { 
		captureAndSaveWarning, 
		generateWhatsAppShareUrl 
	} from '$lib/utils/warningImageStorage';
	
	export let data;
	
	const dispatch = createEventDispatcher();
	
	let isEditing = false;
	let editableWarning = data.warningText;
	let isSending = false;
	let isSaving = false;
	let sendError = null;
	let hasWhatsApp = false;
	let whatsappNumber = '';
	let warningSaved = false; // Flag to prevent duplicate saves
	let currentUserName = ''; // Store current logged-in user name
	let currentUserPosition = ''; // Store current user's position
	let currentUserEmployeeId = null; // Store current user's employee_id
	
	// Workflow state management
	let workflowStep = 'edit'; // 'edit' | 'save' | 'send' | 'share'
	let savedWarningId = null; // Store the warning ID after saving
	let savedImageUrl = null; // Store the image URL after saving
	let isSavingImage = false; // Loading state for image save
	let saveImageError = null; // Error message for image save
	let successMessage = null; // Success message display
	
	// Get current user name and position on mount
	onMount(async () => {
		const user = get(currentUser);
		console.log('🔍 Current user from store:', user);
		if (user) {
			currentUserName = user.username || 'System Administrator';
			currentUserEmployeeId = user.employee_id;
			console.log('🔍 Extracted employee_id:', currentUserEmployeeId);
			
			// If employee_id is not in session, fetch it from database
			if (!currentUserEmployeeId && user.id) {
				console.log('🔍 employee_id not in session, fetching from database...');
				try {
					const { data: userData, error } = await supabase
						.from('users')
						.select('employee_id')
						.eq('id', user.id)
						.single();
					
					if (!error && userData?.employee_id) {
						currentUserEmployeeId = userData.employee_id;
						console.log('✅ Fetched employee_id from database:', currentUserEmployeeId);
					}
				} catch (err) {
					console.error('Error fetching employee_id:', err);
				}
			}
			
			// Fetch user's current position
			if (currentUserEmployeeId) {
				try {
					const { data: positionData, error } = await supabase
						.from('hr_position_assignments')
						.select(`
							position_id,
							hr_positions (
								position_title_en,
								position_title_ar
							)
						`)
						.eq('employee_id', currentUserEmployeeId)
						.eq('is_current', true);
					
					console.log('Position fetch - employee_id:', currentUserEmployeeId);
					console.log('Position fetch - error:', error);
					console.log('Position fetch - data:', positionData);
					
					if (!error && positionData && positionData.length > 0 && positionData[0]?.hr_positions) {
						// Use English position title, or Arabic if English is not available
						currentUserPosition = positionData[0].hr_positions.position_title_en || 
											  positionData[0].hr_positions.position_title_ar || 
											  'Manager';
					} else {
						console.warn('No position found for employee_id:', currentUserEmployeeId);
						currentUserPosition = 'Manager';
					}
				} catch (err) {
					console.error('Error fetching user position:', err);
					currentUserPosition = 'Manager';
				}
			} else {
				console.warn('No employee_id found for current user');
				currentUserPosition = 'Manager';
			}
		}
		await checkWhatsAppContact();
	});

	// Multi-language translations
	const translations = {
		en: {
			companyName: 'AQURA MANAGEMENT SYSTEM',
			documentTitle: 'PERFORMANCE WARNING NOTICE',
			date: 'Date:',
			to: 'To:',
			from: 'From:',
			subject: 'Subject:',
			subjectText: 'Performance Improvement Required',
			taskAssignedBy: 'Task Assigned By:',
			position: 'Position:',
			performanceSummary: 'Performance Summary',
			totalTasksAssigned: 'Total Tasks Assigned:',
			tasksCompleted: 'Tasks Completed:',
			overdueTasks: 'Overdue Tasks:',
			completionRate: 'Completion Rate:',
			warningDetails: 'Warning Details',
			employeeSignature: 'Employee Signature',
			managerSignature: 'Manager Signature',
			edit: 'Edit',
			print: 'Print',
			sendWarning: 'Send Warning',
			sendWhatsApp: 'Send WhatsApp',
			notificationSent: 'Notification sent successfully!',
			whatsappSent: 'WhatsApp message sent!',
			warningSent: 'Warning sent successfully!',
			datePlaceholder: 'Date: ________________',
			improvementRequired: 'Immediate improvement is required to avoid further disciplinary action.',
			documentFooter: 'This document is generated by Aqura Management System',
			name: 'Name:',
			signature: 'Signature:',
			date: 'Date',
			acknowledgmentStatement: 'I acknowledge that I have read and understood the above warning notice. I commit to improving my performance and meeting the required standards.',
			autoGeneratedNote: 'Note: This is an automatically generated document. Physical signatures are not required. Once sent through the internal notification system, this document will be considered as officially signed and acknowledged by both parties.'
		},
		hi: {
			companyName: 'अक्वरा प्रबंधन प्रणाली',
			documentTitle: 'प्रदर्शन चेतावनी सूचना',
			date: 'दिनांक:',
			to: 'को:',
			from: 'से:',
			subject: 'विषय:',
			subjectText: 'प्रदर्शन सुधार आवश्यक',
			taskAssignedBy: 'कार्य सौंपा गया:',
			position: 'पद:',
			performanceSummary: 'प्रदर्शन सारांश',
			totalTasksAssigned: 'कुल सौंपे गए कार्य:',
			tasksCompleted: 'पूर्ण किए गए कार्य:',
			overdueTasks: 'विलंबित कार्य:',
			completionRate: 'पूर्णता दर:',
			warningDetails: 'चेतावनी विवरण',
			employeeSignature: 'कर्मचारी हस्ताक्षर',
			managerSignature: 'प्रबंधक हस्ताक्षर',
			edit: 'संपादित करें',
			print: 'प्रिंट',
			save: 'चेतावनी सहेजें',
			sendWarning: 'चेतावनी भेजें',
			sendWhatsApp: 'व्हाट्सएप भेजें',
			notificationSent: 'सूचना सफलतापूर्वक भेजी गई!',
			whatsappSent: 'व्हाट्सएप संदेश भेजा गया!',
			datePlaceholder: 'दिनांक: ________________',
			improvementRequired: 'अनुशासनात्मक कार्रवाई से बचने के लिए तत्काल सुधार आवश्यक है।',
			documentFooter: 'यह दस्तावेज अक्वरा प्रबंधन प्रणाली द्वारा उत्पन्न किया गया है',
			name: 'नाम:',
			signature: 'हस्ताक्षर:',
			autoGeneratedNote: 'नोट: यह एक स्वचालित रूप से उत्पन्न दस्तावेज है। भौतिक हस्ताक्षर की आवश्यकता नहीं है। आंतरिक अधिसूचना प्रणाली के माध्यम से भेजे जाने के बाद, इस दस्तावेज को दोनों पक्षों द्वारा आधिकारिक रूप से हस्ताक्षरित और स्वीकार किया गया माना जाएगा।',
			acknowledgmentStatement: 'मैं स्वीकार करता/करती हूं कि मैंने उपरोक्त चेतावनी सूचना को पढ़ा और समझा है। मैं अपने प्रदर्शन में सुधार करने और आवश्यक मानकों को पूरा करने के लिए प्रतिबद्ध हूं।'
		},
		ar: {
			companyName: 'نظام إدارة أكورا',
			documentTitle: 'إشعار تحذير الأداء',
			date: 'التاريخ:',
			to: 'إلى:',
			from: 'من:',
			subject: 'الموضوع:',
			subjectText: 'تحسين الأداء مطلوب',
			taskAssignedBy: 'المهمة مكلف بها:',
			position: 'المنصب:',
			performanceSummary: 'ملخص الأداء',
			totalTasksAssigned: 'إجمالي المهام المكلفة:',
			tasksCompleted: 'المهام المكتملة:',
			overdueTasks: 'المهام المتأخرة:',
			completionRate: 'معدل الإنجاز:',
			warningDetails: 'تفاصيل التحذير',
			employeeSignature: 'توقيع الموظف',
			managerSignature: 'توقيع المدير',
			edit: 'تعديل',
			print: 'طباعة',
			save: 'حفظ التحذير',
			sendWarning: 'إرسال تحذير',
			sendWhatsApp: 'إرسال واتساب',
			notificationSent: 'تم إرسال الإشعار بنجاح!',
			whatsappSent: 'تم إرسال رسالة واتساب!',
			datePlaceholder: 'التاريخ: ________________',
			improvementRequired: 'التحسن الفوري مطلوب لتجنب اتخاذ إجراءات تأديبية إضافية.',
			documentFooter: 'تم إنشاء هذا المستند بواسطة نظام إدارة أكورا',
			name: 'الاسم:',
			signature: 'التوقيع:',
			autoGeneratedNote: 'ملاحظة: هذا مستند تم إنشاؤه تلقائياً. التوقيعات الفعلية غير مطلوبة. بمجرد الإرسال عبر نظام الإشعارات الداخلي، سيُعتبر هذا المستند موقعاً ومُقراً به رسمياً من قبل الطرفين.',
			acknowledgmentStatement: 'أقر بأنني قرأت وفهمت إشعار التحذير أعلاه. وألتزم بتحسين أدائي واستيفاء المعايير المطلوبة.'
		},
		ur: {
			companyName: 'اکورا منیجمنٹ سسٹم',
			documentTitle: 'کارکردگی انتباہی نوٹس',
			date: 'تاریخ:',
			to: 'کو:',
			from: 'سے:',
			subject: 'موضوع:',
			subjectText: 'کارکردگی میں بہتری درکار',
			taskAssignedBy: 'کام تفویض کیا گیا:',
			position: 'عہدہ:',
			performanceSummary: 'کارکردگی کا خلاصہ',
			totalTasksAssigned: 'کل تفویض شدہ کام:',
			tasksCompleted: 'مکمل شدہ کام:',
			overdueTasks: 'تاخیر سے کام:',
			completionRate: 'تکمیل کی شرح:',
			warningDetails: 'انتباہ کی تفصیلات',
			employeeSignature: 'ملازم کے دستخط',
			managerSignature: 'منیجر کے دستخط',
			edit: 'ترمیم',
			print: 'پرنٹ',
			sendWarning: 'انتباہ بھیجیں',
			sendWhatsApp: 'واٹس ایپ بھیجیں',
			notificationSent: 'اطلاع کامیابی سے بھیج دی گئی!',
			whatsappSent: 'واٹس ایپ پیغام بھیج دیا گیا!',
			datePlaceholder: 'تاریخ: ________________',
			improvementRequired: 'مزید تادیبی کارروائی سے بچنے کے لیے فوری بہتری درکار ہے۔',
			documentFooter: 'یہ دستاویز اکورا منیجمنٹ سسٹم کے ذریعے تیار کی گئی ہے',
			name: 'نام:',
			signature: 'دستخط:',
			autoGeneratedNote: 'نوٹ: یہ خودکار طور پر تیار کردہ دستاویز ہے۔ جسمانی دستخطوں کی ضرورت نہیں ہے۔ اندرونی اطلاعاتی نظام کے ذریعے بھیجے جانے کے بعد، اس دستاویز کو دونوں فریقوں کی طرف سے باضابطہ طور پر دستخط شدہ اور تسلیم شدہ سمجھا جائے گا۔',
			acknowledgmentStatement: 'میں تسلیم کرتا/کرتی ہوں کہ میں نے مذکورہ بالا تنبیہ نوٹس کو پڑھا اور سمجھا ہے۔ میں اپنی کارکردگی کو بہتر بنانے اور مطلوبہ معیارات کو پورا کرنے کا عہد کرتا/کرتی ہوں۔'
		},
		ta: {
			companyName: 'அக்வரா மேலாண்மை அமைப்பு',
			documentTitle: 'செயல்திறன் எச்சரிக்கை அறிவிப்பு',
			date: 'தேதி:',
			to: 'பெறுநர்:',
			from: 'அனுப்புநர்:',
			subject: 'விषயம்:',
			subjectText: 'செயல்திறன் மேம்பாடு தேவை',
			performanceSummary: 'செயல்திறன் சுருக்கம்',
			totalTasksAssigned: 'மொத்த ஒதுக்கப்பட்ட பணிகள்:',
			tasksCompleted: 'நிறைவேற்றப்பட்ட பணிகள்:',
			overdueTasks: 'தாமதமான பணிகள்:',
			completionRate: 'நிறைவேற்றல் விகிதம்:',
			warningDetails: 'எச்சரிக்கை விவரங்கள்',
			employeeSignature: 'ஊழியர் கையொப்பம்',
			managerSignature: 'மேலாளர் கையொப்பம்',
			edit: 'திருத்து',
			print: 'அச்சிடு',
			sendWarning: 'எச்சரிக்கை அனுப்பு',
			sendWhatsApp: 'வாட்ஸ்அப் அனுப்பு',
			notificationSent: 'அறிவிப்பு வெற்றிகரமாக அனுப்பப்பட்டது!',
			whatsappSent: 'வாட்ஸ்அப் செய்தி அனுப்பப்பட்டது!',
			datePlaceholder: 'தேதி: ________________',
			improvementRequired: 'மேலும் ஒழுங்குமுறை நடவடிக்கையைத் தவிர்க்க உடனடி முன்னேற்றம் தேவை.',
			documentFooter: 'இந்த ஆவணம் அக்வரா மேலாண்மை அமைப்பால் உருவாக்கப்பட்டது',
			autoGeneratedNote: 'குறிப்பு: இது தானாக உருவாக்கப்பட்ட ஆவணம். உடல் கையெழுத்துக்கள் தேவையில்லை. உள் அறிவிப்பு அமைப்பு மூலம் அனுப்பப்பட்டவுடன், இந்த ஆவணம் இரு தரப்பினராலும் அதிகாரப்பூர்வமாக கையொப்பமிடப்பட்டு ஒப்புக்கொள்ளப்பட்டதாக கருதப்படும்.',
			acknowledgmentStatement: 'மேலே உள்ள எச்சரிக்கை அறிவிப்பை நான் படித்து புரிந்துகொண்டேன் என்பதை ஒப்புக்கொள்கிறேன். என் செயல்திறனை மேம்படுத்தவும் தேவையான தரங்களை பூர்த்தி செய்யவும் உறுதியளிக்கிறேன்.'
		},
		ml: {
			companyName: 'അക്വാറ മാനേജ്‌മെന്റ് സിസ്റ്റം',
			documentTitle: 'പ്രകടന മുന്നറിയിപ്പ് അറിയിപ്പ്',
			date: 'തീയതി:',
			to: 'വേണ്ടി:',
			from: 'നിന്ന്:',
			subject: 'വിഷയം:',
			subjectText: 'പ്രകടന മെച്ചപ്പെടുത്തൽ ആവശ്യം',
			performanceSummary: 'പ്രകടന സംഗ്രഹം',
			totalTasksAssigned: 'മൊത്തം നിയോഗിച്ച ജോലികൾ:',
			tasksCompleted: 'പൂർത്തീകരിച്ച ജോലികൾ:',
			overdueTasks: 'കാലഹരണപ്പെട്ട ജോലികൾ:',
			completionRate: 'പൂർത്തീകരണ നിരക്ക്:',
			warningDetails: 'മുന്നറിയിപ്പ് വിശദാംശങ്ങൾ',
			employeeSignature: 'ജീവനക്കാരന്റെ ഒപ്പ്',
			managerSignature: 'മാനേജറുടെ ഒപ്പ്',
			edit: 'എഡിറ്റ്',
			print: 'പ്രിന്റ്',
			sendWarning: 'മുന്നറിയിപ്പ് അയയ്ക്കുക',
			sendWhatsApp: 'വാട്സ്ആപ്പ് അയയ്ക്കുക',
			notificationSent: 'അറിയിപ്പ് വിജയകരമായി അയച്ചു!',
			whatsappSent: 'വാട്സ്ആപ്പ് സന്ദേശം അയച്ചു!',
			datePlaceholder: 'തീയതി: ________________',
			improvementRequired: 'കൂടുതൽ അച്ചടക്ക നടപടികൾ ഒഴിവാക്കാൻ ഉടനടി മെച്ചപ്പെടുത്തൽ ആവശ്യമാണ്.',
			documentFooter: 'ഈ ഡോക്യുമെന്റ് അക്വാറ മാനേജ്‌മെന്റ് സിസ്റ്റം സൃഷ്ടിച്ചതാണ്',
			autoGeneratedNote: 'കുറിപ്പ്: ഇത് യാന്ത്രികമായി സൃഷ്ടിക്കപ്പെട്ട രേഖയാണ്. ഭൗതിക ഒപ്പുകൾ ആവശ്യമില്ല. ആന്തരിക അറിയിപ്പ് സംവിധാനത്തിലൂടെ അയച്ചുകഴിഞ്ഞാൽ, ഈ രേഖ ഇരു കക്ഷികളും ഔദ്യോഗികമായി ഒപ്പിടുകയും അംഗീകരിക്കുകയും ചെയ്തതായി കണക്കാക്കപ്പെടും.',
			acknowledgmentStatement: 'മുകളിൽ പറഞ്ഞ മുന്നറിയിപ്പ് അറിയിപ്പ് ഞാൻ വായിക്കുകയും മനസ്സിലാക്കുകയും ചെയ്തു എന്ന് ഞാൻ അംഗീകരിക്കുന്നു. എന്റെ പ്രകടനം മെച്ചപ്പെടുത്താനും ആവശ്യമായ മാനദണ്ഡങ്ങൾ പാലിക്കാനും ഞാൻ പ്രതിജ്ഞാബദ്ധനാണ്.'
		},
		bn: {
			companyName: 'আকুরা ম্যানেজমেন্ট সিস্টেম',
			documentTitle: 'কর্মক্ষমতা সতর্কতা নোটিশ',
			date: 'তারিখ:',
			to: 'প্রতি:',
			from: 'হতে:',
			subject: 'বিষয়:',
			subjectText: 'কর্মক্ষমতা উন্নতি প্রয়োজন',
			performanceSummary: 'কর্মক্ষমতা সারসংক্ষেপ',
			totalTasksAssigned: 'মোট নিযুক্ত কাজ:',
			tasksCompleted: 'সম্পন্ন কাজ:',
			overdueTasks: 'বিলম্বিত কাজ:',
			completionRate: 'সমাপ্তির হার:',
			warningDetails: 'সতর্কতার বিশদ',
			employeeSignature: 'কর্মচারীর স্বাক্ষর',
			managerSignature: 'ম্যানেজারের স্বাক্ষর',
			edit: 'সম্পাদনা',
			print: 'মুদ্রণ',
			sendWarning: 'সতর্কতা পাঠান',
			sendWhatsApp: 'হোয়াটসঅ্যাপ পাঠান',
			notificationSent: 'বিজ্ঞপ্তি সফলভাবে পাঠানো হয়েছে!',
			whatsappSent: 'হোয়াটসঅ্যাপ বার্তা পাঠানো হয়েছে!',
			datePlaceholder: 'তারিখ: ________________',
			improvementRequired: 'আরও শাস্তিমূলক ব্যবস্থা এড়াতে তাৎক্ষণিক উন্নতি প্রয়োজন।',
			documentFooter: 'এই নথিটি আকুরা ম্যানেজমেন্ট সিস্টেম দ্বারা তৈরি',
			autoGeneratedNote: 'নোট: এটি একটি স্বয়ংক্রিয়ভাবে তৈরি নথি। শারীরিক স্বাক্ষরের প্রয়োজন নেই। অভ্যন্তরীণ বিজ্ঞপ্তি ব্যবস্থার মাধ্যমে পাঠানোর পরে, এই নথিটি উভয় পক্ষ দ্বারা আনুষ্ঠানিকভাবে স্বাক্ষরিত এবং স্বীকৃত হিসাবে বিবেচিত হবে।',
			acknowledgmentStatement: 'আমি স্বীকার করছি যে আমি উপরের সতর্কতা নোটিশটি পড়েছি এবং বুঝেছি। আমি আমার পারফরম্যান্স উন্নত করতে এবং প্রয়োজনীয় মান পূরণ করতে প্রতিশ্রুতিবদ্ধ।'
		}
	};

	// Get current language translations
	$: t = translations[data.language] || translations.en;

	// Check if user has WhatsApp contact
	async function checkWhatsAppContact() {
		try {
			let userData = null;
			let userError = null;

			// First try to get user by username if available
			if (data.recipientUsername && data.recipientUsername !== 'Unknown') {
				const result = await supabase
					.from('users')
					.select('employee_id, username')
					.eq('username', data.recipientUsername)
					.single();
				
				userData = result.data;
				userError = result.error;
			}

			// If username lookup failed or no username, try by user ID
			if ((!userData || userError) && data.recipientUserId) {
				console.log('Trying user lookup by ID:', data.recipientUserId);
				const result = await supabase
					.from('users')
					.select('employee_id, username')
					.eq('id', data.recipientUserId)
					.single();
				
				userData = result.data;
				userError = result.error;
			}

			if (userError || !userData?.employee_id) {
				console.log('No employee_id found for user:', data.recipientUsername, 'or user ID:', data.recipientUserId);
				return;
			}

			// Then get the employee's contact information
			const { data: contactData, error } = await supabase
				.from('hr_employee_contacts')
				.select('whatsapp_number')
				.eq('employee_id', userData.employee_id)
				.single();

			if (contactData && contactData.whatsapp_number) {
				hasWhatsApp = true;
				whatsappNumber = contactData.whatsapp_number;
			}
		} catch (err) {
			console.error('Error checking WhatsApp contact:', err);
		}
	}

	function toggleEdit() {
		if (isEditing) {
			// Save changes
			data.warningText = editableWarning;
		}
		isEditing = !isEditing;
	}

	// Function to lookup user ID by username
	async function lookupUserIdByUsername(username) {
		try {
			console.log(`Looking up user ID for username: ${username}`);
			
			// First try the users table
			const { data: userData, error: userError } = await supabase
				.from('users')
				.select('id')
				.eq('username', username)
				.single();

			if (userData && !userError) {
				console.log(`Found user ID ${userData.id} for username ${username}`);
				return userData.id;
			}

			// If not found in users table, try hr_employees table
			const { data: hrData, error: hrError } = await supabase
				.from('hr_employees')
				.select('id')
				.eq('username', username)
				.single();

			if (hrData && !hrError) {
				console.log(`Found employee ID ${hrData.id} for username ${username}`);
				return hrData.id;
			}

			console.warn(`No user ID found for username: ${username}`);
			return null;
		} catch (error) {
			console.error(`Error looking up user ID for username ${username}:`, error);
			return null;
		}
	}

	async function sendInternalNotification() {
		isSending = true;
		sendError = null;

		try {
			// WARNING RECORD MUST ALREADY BE SAVED BEFORE CALLING THIS
			// This function should only be called after saveAsImage() has saved the record
			if (!warningSaved || !savedWarningId) {
				throw new Error('Warning record must be saved before sending notification. Please use Save Image button first.');
			}

			// Determine the target user ID - try multiple possible fields
			let targetUserId = data.recipientUserId || 
							   data.assignmentData?.assigned_to_user_id || 
							   data.assignmentData?.assignedToUserId ||
							   data.assignmentData?.user_id ||
							   data.assignmentData?.userId;

			if (!targetUserId) {
				// If we still don't have a user ID, try to look it up by username
				const username = data.recipientUsername || data.assignmentData?.assigned_to_username || data.assignmentData?.assigned_to;
				if (username) {
					console.warn(`No user ID found for notification target. Attempting to look up user ID for username: ${username}`);
					targetUserId = await lookupUserIdByUsername(username);
					
					if (!targetUserId) {
						throw new Error(`No valid user ID found for notification target "${username}". User ID is required for push notifications.`);
					}
				} else {
					throw new Error('No valid user ID or username found for notification target');
				}
			}

			// Create notification using notificationManagement for proper push notification support
			const notificationData = {
				title: 'Performance Warning',
				message: `Warning: Performance Review Required\n\n${editableWarning}`,
				type: 'warning',
				priority: 'high',
				target_type: 'specific_users',
				target_users: [targetUserId]
			};

			// Use assigned_by or current user for createdBy - handle undefined case
			const createdBy = data.assignedBy || 
							  data.assignmentData?.assigned_by || 
							  'System Administrator';

			await notificationManagement.createNotification(notificationData, createdBy);

			// Don't close modal automatically - let workflow continue
			console.log('✅ Notification sent successfully');
		} catch (err) {
			console.error('Error sending notification:', err);
			sendError = 'Failed to send notification: ' + err.message;
		} finally {
			isSending = false;
		}
	}

	async function saveWarningRecord() {
		if (warningSaved) {
			console.log('Warning already saved, skipping duplicate save');
			return;
		}

		try {
			// Get current user information from persistent auth
			const user = get(currentUser);
			
			if (!user) {
				throw new Error('User not authenticated');
			}

			// Get the employee information from the user_id to properly link the employee
			let employeeId = null;
			let actualUsername = null;
			let actualUserId = null;
			
			// First try to get user ID from data, then lookup by username if needed
			actualUserId = data.recipientUserId || 
						   data.assignmentData?.assigned_to_user_id || 
						   data.assignmentData?.assignedToUserId;
			
			if (!actualUserId) {
				// Try to lookup user ID by username
				const username = data.recipientUsername || data.assignmentData?.assigned_to_username || data.assignmentData?.assigned_to;
				if (username) {
					actualUserId = await lookupUserIdByUsername(username);
				}
			}
			
			if (actualUserId) {
				try {
					// Get user details to find linked employee
					const { data: userDetails, error: userError } = await supabase
						.from('users')
						.select(`
							id,
							username,
							employee_id,
							hr_employees(id, name, employee_id)
						`)
						.eq('id', actualUserId)
						.single();
					
					if (!userError && userDetails) {
						actualUsername = userDetails.username;
						employeeId = userDetails.employee_id; // This is the UUID from users.employee_id
						console.log('Found user details:', {
							userId: userDetails.id,
							username: userDetails.username,
							employeeId: userDetails.employee_id,
							employeeData: userDetails.hr_employees
						});
					} else {
						console.warn('Could not find user details for ID:', actualUserId);
					}
				} catch (err) {
					console.error('Error fetching user details:', err);
				}
			}

			// Prepare warning record data matching the database schema
			const warningRecord = {
				user_id: actualUserId, // Use the looked-up user ID
				employee_id: employeeId, // Now properly linked to hr_employees table
				username: actualUsername || data.recipientUsername || data.assignmentData?.assigned_to || 'unknown_user',
				warning_type: data.warningType,
				has_fine: data.hasFine || false,
				fine_amount: data.fineAmount || null,
				fine_currency: data.fineCurrency || 'USD',
				fine_status: data.hasFine ? 'pending' : null,
				warning_text: editableWarning,
				language_code: data.language || 'en',
				task_id: data.assignmentData?.taskId || data.assignmentData?.task_id || null,
				task_title: data.assignmentData?.taskTitle || data.assignmentData?.task_title || null,
				task_description: data.assignmentData?.taskDescription || data.assignmentData?.task_description || null,
				assignment_id: data.assignmentData?.assignmentId || data.assignmentData?.assignment_id || data.assignmentData?.id || null,
				total_tasks_assigned: data.totalAssigned || data.assignmentData?.total_assigned || 0,
				total_tasks_completed: data.totalCompleted || data.assignmentData?.total_completed || 0,
				total_tasks_overdue: data.totalOverdue || data.assignmentData?.total_overdue || 0,
				completion_rate: data.completionRate || 0,
				issued_by: user?.id || 'system',
				issued_by_username: user?.username || 'system',
				warning_status: 'active',
				branch_id: data.assignmentData?.branchId || data.assignmentData?.branch_id || null,
				severity_level: determineSeverityLevel(),
				follow_up_required: data.hasFine || data.completionRate < 50,
				follow_up_date: data.hasFine ? new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] : null // 7 days from now
			};

			console.log('Saving warning record:', warningRecord);

			// Use admin client to bypass RLS since we have custom authentication
			const { data: insertedData, error } = await supabase
				.from('employee_warnings')
				.insert([warningRecord])
				.select()
				.single();

			if (error) {
				console.error('Database error:', error);
				throw new Error(`Failed to save warning record: ${error.message}`);
			}

			console.log('Warning record saved successfully:', insertedData);
			warningSaved = true; // Set flag after successful save
			savedWarningId = insertedData.id; // Store the ID
			return insertedData; // Return the inserted data
		} catch (err) {
			console.error('Error saving warning record:', err);
			// Don't set warningSaved flag if save failed
			throw err;
		}
	}

	function determineSeverityLevel() {
		const completionRate = data.completionRate || 0;
		const hasFine = data.hasFine || false;
		
		if (hasFine && completionRate < 30) return 'critical';
		if (hasFine || completionRate < 40) return 'high';
		if (completionRate < 60) return 'medium';
		return 'low';
	}

	async function sendWarning() {
		if (isSending || isSaving) return;
		
		isSending = true;
		sendError = '';
		
		try {
			// WARNING: This is the OLD workflow function
			// The new workflow requires saving via saveAsImage() first
			// This function should not be called anymore but kept for backwards compatibility
			if (!warningSaved || !savedWarningId) {
				throw new Error('Warning record must be saved first. Please use Save Image button.');
			}
			
			// Then send the notification
			await sendInternalNotification();
			
			// Show success message
			alert(t.warningSent || 'Warning sent successfully!');
			
			// Close modal after successful send
			dispatch('close');
			
		} catch (err) {
			console.error('Error sending warning:', err);
			sendError = 'Failed to send warning: ' + err.message;
		} finally {
			isSending = false;
		}
	}

	function sendToWhatsApp() {
		if (!hasWhatsApp || !whatsappNumber) {
			alert('WhatsApp number not available for this employee');
			return;
		}

		// NEW WORKFLOW: Record must already be saved via saveAsImage()
		if (!warningSaved || !savedWarningId) {
			alert('Please save the warning as image first before sharing to WhatsApp');
			return;
		}
		
		// Generate WhatsApp message
		const message = generateWhatsAppMessage();
		const encodedMessage = encodeURIComponent(message);
		const whatsappUrl = `https://web.whatsapp.com/send?phone=${whatsappNumber}&text=${encodedMessage}`;
		
		// Open WhatsApp Web in new tab
		window.open(whatsappUrl, '_blank');
	}

	function generateWhatsAppMessage() {
		return `*${t.documentTitle}*

${t.to} ${data.recipientName},

*${t.warningDetails}:*
${editableWarning}

---
${t.from} ${currentUserName} (${currentUserPosition})
*Task Assigned By:* ${data.assignedBy}
${t.date} ${new Date().toLocaleDateString()}

${t.companyName}`;
	}

	function printTemplate() {
		// NEW WORKFLOW: Record should already be saved via saveAsImage()
		// But printing doesn't require the record to be saved, so we can allow it
		const printWindow = window.open('', '_blank');
		const printContent = generatePrintableHTML();
		
		printWindow.document.write(printContent);
		printWindow.document.close();
		printWindow.print();
	}

	function generatePrintableHTML() {
		const currentDate = new Date().toLocaleDateString();
		const logoUrl = `${window.location.origin}/icons/logo.png`;
		
		return `
		<!DOCTYPE html>
		<html>
		<head>
			<title>${t.documentTitle}</title>
			<style>
				@page {
					size: A4;
					margin: 20mm;
				}
				body {
					font-family: Arial, sans-serif;
					margin: 0;
					padding: 0;
					line-height: 1.4;
					color: #333;
					font-size: 12px;
				}
				.header {
					text-align: center;
					margin-bottom: 25px;
					border-bottom: 2px solid #333;
					padding-bottom: 15px;
				}
				.logo-container {
					width: 80px;
					height: 40px;
					margin: 0 auto 12px;
					display: flex;
					align-items: center;
					justify-content: center;
				}
				.company-logo {
					max-width: 100%;
					max-height: 100%;
					object-fit: contain;
				}
				.company-name {
					font-size: 18px;
					font-weight: 700;
					color: #111827;
					margin: 0;
				}
				.document-title {
					font-size: 16px;
					font-weight: 700;
					color: #dc2626;
					margin: 12px 0 0 0;
					letter-spacing: 0.5px;
				}
				.logo-container {
					width: 80px;
					height: 40px;
					margin: 0 auto 10px;
					display: flex;
					align-items: center;
					justify-content: center;
				}
				.company-logo {
					max-width: 100%;
					max-height: 100%;
					object-fit: contain;
				}
				.company-name {
					font-size: 16px;
					font-weight: bold;
					margin: 5px 0;
				}
				.document-title {
					font-size: 14px;
					font-weight: bold;
					color: #d32f2f;
					margin: 10px 0;
				}
				.content {
					margin: 20px 0;
				}
				.warning-content {
					background: #fff3cd;
					border: 1px solid #ffeaa7;
					padding: 15px;
					margin: 15px 0;
					border-radius: 4px;
					font-size: 11px;
				}
				.statistics {
					display: grid;
					grid-template-columns: repeat(2, 1fr);
					gap: 8px;
					margin: 15px 0;
					padding: 12px;
					background: #f8f9fa;
					border-radius: 4px;
					font-size: 11px;
				}
				.stat-item {
					display: flex;
					justify-content: space-between;
				}
				.signatures {
					margin-top: 30px;
					display: grid;
					grid-template-columns: 1fr 1fr;
					gap: 20px;
					font-size: 11px;
				}
				.signature-section {
					text-align: center;
				}
				.signature-line {
					border-top: 1px solid #333;
					margin-top: 25px;
					padding-top: 5px;
				}
				.footer {
					margin-top: 20px;
					text-align: center;
					font-size: 10px;
					color: #666;
				}
				@media print {
					body { 
						margin: 0; 
						font-size: 11px;
					}
					.header {
						margin-bottom: 20px;
						padding-bottom: 10px;
					}
				}
			</style>
		</head>
		<body>
			<div class="header">
				<div class="logo-container">
					<img src="${logoUrl}" alt="Company Logo" class="company-logo" />
				</div>
				<div class="company-name">${t.companyName}</div>
				<div class="document-title">${t.documentTitle}</div>
			</div>
			
			<div class="content">
				<p><strong>${t.date}</strong> ${currentDate}</p>
				<p><strong>${t.from}</strong> ${currentUserName} (${currentUserPosition})</p>
				<p><strong>${t.to}</strong> ${data.recipientName}</p>
				<p><strong>${t.subject}</strong> ${t.subjectText}</p>
				<p><strong>${t.taskAssignedBy || 'Task Assigned By:'}</strong> ${data.assignedBy}</p>
				
				<div class="warning-content">
					${editableWarning.split('\n').slice(0, 10).map(line => `<p style="margin: 5px 0;">${line}</p>`).join('')}
				</div>
				
				<p style="margin-top: 15px; font-size: 11px;">${t.improvementRequired}</p>
			</div>
			
			<div class="signatures">
				<div style="max-width: 500px; margin: 30px auto; padding: 20px; border: 2px solid #e5e7eb; border-radius: 8px; background: #ffffff;">
					<div style="text-align: center; font-weight: 600; font-size: 16px; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 2px solid #3b82f6;">
						${t.employeeSignature}
					</div>
					<div style="background: #f0f9ff; border-left: 4px solid #3b82f6; padding: 12px; margin-bottom: 20px; font-size: 12px; line-height: 1.5; color: #1e40af; font-style: italic;">
						${t.acknowledgmentStatement || 'I acknowledge that I have read and understood the above warning notice. I commit to improving my performance and meeting the required standards.'}
					</div>
					<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
						<div>
							<div style="font-weight: 600; font-size: 12px; margin-bottom: 8px;">${t.date || 'Date'}:</div>
							<div style="border-bottom: 2px solid #9ca3af; padding: 10px 0; min-height: 35px;">________________</div>
						</div>
						<div>
							<div style="font-weight: 600; font-size: 12px; margin-bottom: 8px;">${t.signature || 'Signature'}:</div>
							<div style="border-bottom: 2px solid #9ca3af; padding: 10px 0; min-height: 35px;">________________</div>
						</div>
					</div>
				</div>
			</div>
			
			<div class="auto-note" style="margin-top: 20px; padding: 12px; background: #f3f4f6; border-left: 4px solid #6366f1; font-size: 10px; line-height: 1.5; color: #4b5563; font-style: italic;">
				<p style="margin: 0;">${t.autoGeneratedNote}</p>
			</div>
			
			<div class="footer">
				<p>${t.documentFooter}</p>
			</div>
		</body>
		</html>`;
	}

	/**
	 * New Workflow Functions
	 */
	
	// Step 1: Save warning as image
	async function saveAsImage() {
		if (isSavingImage) return;
		
		isSavingImage = true;
		saveImageError = null;
		
		try {
			// First save the warning record to database if not already saved
			let warningData;
			if (!warningSaved) {
				warningData = await saveWarningRecord();
			} else {
				// Fetch existing warning data
				const { data: existingWarning } = await supabase
					.from('employee_warnings')
					.select('*')
					.eq('id', savedWarningId)
					.single();
				warningData = existingWarning;
			}
			
			if (!warningData) {
				throw new Error('Failed to get warning data');
			}
			
			// Get the template body element for capture
			const templateBody = document.querySelector('.template-body');
			if (!templateBody) {
				throw new Error('Template body not found');
			}
			
			// Get employee information
			const employeeName = data.recipientName || warningData.username || 'Unknown';
			const employeeId = warningData.employee_id || null;
			
			console.log('📸 Capturing warning for:', employeeName, '(ID:', employeeId, ')');
			
			// Capture and upload the image with employee details
			const result = await captureAndSaveWarning(
				templateBody, 
				warningData.id, 
				warningData.warning_reference,
				employeeName,
				employeeId
			);
			
			if (!result.success) {
				throw new Error(result.error);
			}
			
			// Store the image URL
			savedImageUrl = result.imageUrl;
			savedWarningId = result.warningId;
			
			// Move to next step
			workflowStep = 'send';
			
			successMessage = '✅ Warning saved as image successfully!';
			setTimeout(() => successMessage = null, 3000);
		} catch (err) {
			console.error('Error saving warning as image:', err);
			saveImageError = err.message;
		} finally {
			isSavingImage = false;
		}
	}
	
	// Step 2: Send notification (existing functionality, modified)
	async function sendNotificationWithImage() {
		if (isSending) return;
		
		isSending = true;
		sendError = null;
		
		try {
			// Ensure we have the saved image
			if (!savedImageUrl) {
				throw new Error('Please save the warning as image first');
			}
			
			// Send notification with image URL
			await sendInternalNotification();
			
			// Move to next step
			workflowStep = 'share';
			
			// Success message - use a better notification instead of alert
			successMessage = '✅ Notification sent successfully!';
			setTimeout(() => successMessage = null, 3000);
		} catch (err) {
			console.error('Error sending notification:', err);
			sendError = 'Failed to send notification: ' + err.message;
		} finally {
			isSending = false;
		}
	}
	
	// Step 3: Share to WhatsApp
	function shareToWhatsApp() {
		if (!savedImageUrl) {
			alert('Please save and send the warning first');
			return;
		}
		
		// Generate WhatsApp message with image link
		const whatsappUrl = generateWhatsAppShareUrl(
			savedImageUrl,
			data.recipientName,
			`*${t.documentTitle}*\n\n${t.to} ${data.recipientName},\n\n${t.warningDetails}\n\nView document: ${savedImageUrl}\n\n${t.from} ${currentUserName} (${currentUserPosition})\n${t.date} ${new Date().toLocaleDateString()}\n\n${t.companyName}`
		);
		
		// Open WhatsApp Web
		window.open(whatsappUrl, '_blank');
	}

	function closeModal() {
		dispatch('close');
	}
</script>

<div class="template-overlay" on:click={closeModal}>
	<div class="template-content" on:click|stopPropagation>
		<div class="template-header">
			<div class="header-left">
				<h2 class="template-title">Warning Template</h2>
				<span class="language-badge">{data.language.toUpperCase()}</span>
			</div>
			<div class="header-right">
				<button class="edit-btn" on:click={toggleEdit}>
					{#if isEditing}
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
						</svg>
						Save
					{:else}
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"/>
						</svg>
						{t.edit}
					{/if}
				</button>
				<button class="print-btn" on:click={printTemplate}>
					<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/>
					</svg>
					{t.print}
				</button>
				<button class="close-btn" on:click={closeModal}>
					<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
					</svg>
				</button>
			</div>
		</div>

		<div class="template-body">
			<!-- Template Header Section -->
			<div class="document-header">
				<div class="logo-section">
					<div class="logo-container">
						<img src="/icons/logo.png" alt="Company Logo" class="company-logo" />
					</div>
					<h3 class="company-name">{t.companyName}</h3>
				</div>
				<h2 class="document-title">{t.documentTitle}</h2>
			</div>

			<!-- Document Details -->
			<div class="document-details">
				<div class="detail-row">
					<span class="detail-label">{t.date}</span>
					<span class="detail-value">{new Date().toLocaleDateString()}</span>
				</div>
				<div class="detail-row">
					<span class="detail-label">{t.from}</span>
					<span class="detail-value">{currentUserName} ({currentUserPosition})</span>
				</div>
				<div class="detail-row">
					<span class="detail-label">{t.to}</span>
					<span class="detail-value">{data.recipientName} ({data.recipientUsername})</span>
				</div>
				<div class="detail-row">
					<span class="detail-label">{t.subject}</span>
					<span class="detail-value">{t.subjectText}</span>
				</div>
				<div class="detail-row">
					<span class="detail-label">{t.taskAssignedBy || 'Task Assigned By:'}</span>
					<span class="detail-value">{data.assignedBy}</span>
				</div>
			</div>

			<!-- Warning Content -->
			<div class="warning-section">
				<h4 class="section-title">{t.warningDetails}</h4>
				{#if isEditing}
					<textarea 
						bind:value={editableWarning}
						class="warning-textarea"
						rows="8"
						placeholder="Enter warning text..."
					></textarea>
				{:else}
					<div class="warning-text">
						{#each editableWarning.split('\n') as line}
							<p>{line}</p>
						{/each}
					</div>
				{/if}
			</div>

			<!-- Signature Section -->
			<div class="signature-section">
				<div class="signature-card">
					<h5 class="signature-title">{t.employeeSignature}</h5>
					<div class="acknowledgment-text">
						{t.acknowledgmentStatement || 'I acknowledge that I have read and understood the above warning notice. I commit to improving my performance and meeting the required standards.'}
					</div>
					<div class="signature-fields">
						<div class="signature-field">
							<label>{t.date || 'Date'}:</label>
							<div class="field-line">________________</div>
						</div>
						<div class="signature-field">
							<label>{t.signature || 'Signature'}:</label>
							<div class="field-line">________________</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Auto-Generated Document Note -->
			<div class="auto-generated-note">
				<p>{t.autoGeneratedNote}</p>
			</div>
		</div>

		<!-- Error Messages -->
		{#if sendError}
			<div class="error-message">
				{sendError}
			</div>
		{/if}
		{#if saveImageError}
			<div class="error-message">
				{saveImageError}
			</div>
		{/if}

		<!-- Success Message -->
		{#if successMessage}
			<div class="success-message">
				{successMessage}
			</div>
		{/if}

		<!-- Action Buttons - Workflow -->
		<div class="template-footer">
			<div class="action-buttons">
				<!-- Step 1: Save as Image -->
				{#if workflowStep === 'edit' || workflowStep === 'save'}
					<button 
						class="action-btn save-image-btn"
						on:click={saveAsImage}
						disabled={isSavingImage}
					>
						{#if isSavingImage}
							<div class="loading-spinner"></div>
						{:else}
							<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/>
							</svg>
						{/if}
						💾 Save as Image
					</button>
				{/if}
				
				<!-- Step 2: Send Notification -->
				{#if workflowStep === 'send'}
					<button 
						class="action-btn notification-btn"
						on:click={sendNotificationWithImage}
						disabled={isSending}
					>
						{#if isSending}
							<div class="loading-spinner"></div>
						{:else}
							<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"/>
							</svg>
						{/if}
						📤 Send Notification
					</button>
				{/if}
				
				<!-- Step 3: Share to WhatsApp -->
				{#if workflowStep === 'share'}
					<div class="share-section">
						<button 
							class="action-btn whatsapp-btn"
							on:click={shareToWhatsApp}
						>
							<svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
								<path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893A11.821 11.821 0 0020.885 3.106"/>
							</svg>
							📱 Share to WhatsApp
						</button>
						<div class="image-link-section">
							<span class="link-label">Saved Image:</span>
							<a href={savedImageUrl} target="_blank" class="image-link">
								View Image 🔗
							</a>
						</div>
					</div>
				{/if}
				
				<!-- Workflow Progress Indicator -->
				<div class="workflow-progress">
					<div class="progress-step" class:active={workflowStep === 'save' || workflowStep === 'edit'}>
						<span class="step-number">1</span>
						<span class="step-label">Save</span>
					</div>
					<div class="progress-line" class:completed={workflowStep === 'send' || workflowStep === 'share'}></div>
					<div class="progress-step" class:active={workflowStep === 'send'} class:completed={workflowStep === 'share'}>
						<span class="step-number">2</span>
						<span class="step-label">Send</span>
					</div>
					<div class="progress-line" class:completed={workflowStep === 'share'}></div>
					<div class="progress-step" class:active={workflowStep === 'share'}>
						<span class="step-number">3</span>
						<span class="step-label">Share</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<style>
	.template-overlay {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background: rgba(0, 0, 0, 0.6);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1001;
	}

	.template-content {
		background: white;
		border-radius: 12px;
		box-shadow: 0 25px 50px rgba(0, 0, 0, 0.15);
		width: 95%;
		max-width: 900px;
		max-height: 95vh;
		overflow-y: auto;
		position: relative;
	}

	.template-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 20px 24px;
		border-bottom: 1px solid #e5e7eb;
		position: sticky;
		top: 0;
		background: white;
		z-index: 10;
	}

	.header-left {
		display: flex;
		align-items: center;
		gap: 12px;
	}

	.template-title {
		font-size: 20px;
		font-weight: 600;
		color: #111827;
		margin: 0;
	}

	.language-badge {
		background: #3b82f6;
		color: white;
		padding: 4px 8px;
		border-radius: 4px;
		font-size: 12px;
		font-weight: 600;
	}

	.header-right {
		display: flex;
		align-items: center;
		gap: 8px;
	}

	.edit-btn, .print-btn, .close-btn {
		display: flex;
		align-items: center;
		gap: 4px;
		padding: 6px 12px;
		border: 1px solid #d1d5db;
		background: white;
		color: #374151;
		border-radius: 6px;
		font-size: 14px;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.edit-btn:hover, .print-btn:hover {
		background: #f9fafb;
		border-color: #9ca3af;
	}

	.close-btn {
		border-color: transparent;
		color: #6b7280;
	}

	.close-btn:hover {
		background: #f3f4f6;
		color: #374151;
	}

	.template-body {
		padding: 20px;
		max-width: 210mm;
		min-height: 297mm;
		margin: 0 auto;
		background: white;
		box-shadow: 0 0 10px rgba(0,0,0,0.1);
	}

	.document-header {
		text-align: center;
		margin-bottom: 20px;
		padding-bottom: 15px;
		border-bottom: 2px solid #111827;
	}

	.logo-section {
		margin-bottom: 20px;
	}

	.logo-placeholder {
		width: 120px;
		height: 60px;
		background: #f3f4f6;
		border: 2px dashed #9ca3af;
		margin: 0 auto 16px;
		display: flex;
		align-items: center;
		justify-content: center;
		color: #6b7280;
		font-size: 12px;
		font-weight: 600;
		border-radius: 8px;
	}

	.logo-container {
		width: 80px;
		height: 40px;
		margin: 0 auto 12px;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.company-logo {
		max-width: 100%;
		max-height: 100%;
		object-fit: contain;
	}

	.company-name {
		font-size: 18px;
		font-weight: 700;
		color: #111827;
		margin: 0;
	}

	.document-title {
		font-size: 16px;
		font-weight: 700;
		color: #dc2626;
		margin: 12px 0 0 0;
		letter-spacing: 0.5px;
	}

	.document-details {
		margin-bottom: 24px;
		padding: 20px;
		background: #f9fafb;
		border-radius: 8px;
	}

	.detail-row {
		display: flex;
		margin-bottom: 8px;
	}

	.detail-row:last-child {
		margin-bottom: 0;
	}

	.detail-label {
		font-weight: 600;
		color: #374151;
		min-width: 80px;
	}

	.detail-value {
		color: #111827;
	}

	.signature-section, .warning-section, .signature-section {
		margin-bottom: 32px;
	}

	.signature-card {
		max-width: 600px;
		margin: 0 auto;
		padding: 24px;
		background: #ffffff;
		border: 2px solid #e5e7eb;
		border-radius: 12px;
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
	}

	.signature-title {
		font-size: 18px;
		font-weight: 600;
		color: #111827;
		margin: 0 0 16px 0;
		text-align: center;
		padding-bottom: 12px;
		border-bottom: 2px solid #3b82f6;
	}

	.acknowledgment-text {
		background: #f0f9ff;
		border-left: 4px solid #3b82f6;
		padding: 16px;
		margin-bottom: 24px;
		border-radius: 4px;
		font-size: 14px;
		line-height: 1.6;
		color: #1e40af;
		font-style: italic;
	}

	.signature-fields {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 24px;
	}

	.signature-field {
		display: flex;
		flex-direction: column;
		gap: 8px;
	}

	.signature-field label {
		font-weight: 600;
		color: #374151;
		font-size: 14px;
	}

	.field-line {
		padding: 12px 0;
		border-bottom: 2px solid #9ca3af;
		min-height: 40px;
		color: #6b7280;
		font-size: 14px;
	}

	.section-title {
		font-size: 18px;
		font-weight: 600;
		color: #111827;
		margin: 0 0 16px 0;
		padding-bottom: 8px;
		border-bottom: 1px solid #e5e7eb;
	}

	.stats-grid {
		display: grid;
		grid-template-columns: repeat(2, 1fr);
		gap: 16px;
		padding: 20px;
		background: #f8fafc;
		border-radius: 8px;
		border: 1px solid #e2e8f0;
	}

	.stat-item {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.stat-label {
		font-weight: 500;
		color: #475569;
	}

	.stat-value {
		font-weight: 700;
		color: #111827;
	}

	.stat-completed {
		color: #059669;
	}

	.stat-overdue {
		color: #dc2626;
	}

	.warning-textarea {
		width: 100%;
		padding: 16px;
		border: 1px solid #d1d5db;
		border-radius: 8px;
		font-size: 14px;
		line-height: 1.6;
		resize: vertical;
		min-height: 200px;
	}

	.warning-textarea:focus {
		outline: none;
		border-color: #3b82f6;
		box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
	}

	.warning-text {
		padding: 20px;
		background: #fff3cd;
		border: 1px solid #ffeaa7;
		border-radius: 8px;
		line-height: 1.6;
	}

	.auto-generated-note {
		margin-top: 30px;
		padding: 16px;
		background: #f3f4f6;
		border-left: 4px solid #6366f1;
		border-radius: 4px;
		font-size: 12px;
		line-height: 1.6;
		color: #4b5563;
		font-style: italic;
	}

	.auto-generated-note p {
		margin: 0;
	}

	.warning-text p {
		margin: 0 0 12px 0;
		color: #111827;
	}

	.warning-text p:last-child {
		margin-bottom: 0;
	}

	.error-message {
		background: #fef2f2;
		border: 1px solid #fecaca;
		color: #dc2626;
		padding: 16px;
		margin: 16px 24px;
		border-radius: 8px;
		font-size: 14px;
	}

	.success-message {
		background: #f0fdf4;
		border: 1px solid #bbf7d0;
		color: #16a34a;
		padding: 16px;
		margin: 16px 24px;
		border-radius: 8px;
		font-size: 14px;
		font-weight: 500;
		animation: slideIn 0.3s ease-out;
	}

	@keyframes slideIn {
		from {
			opacity: 0;
			transform: translateY(-10px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	.template-footer {
		padding: 24px;
		border-top: 1px solid #e5e7eb;
		background: #f9fafb;
		border-bottom-left-radius: 12px;
		border-bottom-right-radius: 12px;
	}

	.action-buttons {
		display: flex;
		gap: 12px;
		justify-content: center;
		flex-wrap: wrap;
	}

	.action-btn {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 12px 20px;
		border: none;
		border-radius: 8px;
		font-size: 14px;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.notification-btn {
		background: #3b82f6;
		color: white;
	}

	.notification-btn:hover:not(:disabled) {
		background: #2563eb;
	}

	.notification-btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.whatsapp-btn {
		background: #25d366;
		color: white;
	}

	.whatsapp-btn:hover {
		background: #20ba5a;
	}

	.save-image-btn {
		background: #8b5cf6;
		color: white;
	}

	.save-image-btn:hover:not(:disabled) {
		background: #7c3aed;
	}

	.save-image-btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.share-section {
		display: flex;
		flex-direction: column;
		gap: 12px;
		align-items: center;
		width: 100%;
	}

	.image-link-section {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 8px 16px;
		background: #f0fdf4;
		border: 1px solid #bbf7d0;
		border-radius: 6px;
		font-size: 13px;
	}

	.link-label {
		color: #166534;
		font-weight: 500;
	}

	.image-link {
		color: #2563eb;
		text-decoration: none;
		font-weight: 600;
		display: flex;
		align-items: center;
		gap: 4px;
		transition: color 0.2s;
	}

	.image-link:hover {
		color: #1d4ed8;
		text-decoration: underline;
	}

	.workflow-progress {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 12px;
		margin-top: 24px;
		padding-top: 20px;
		border-top: 1px solid #e5e7eb;
		width: 100%;
	}

	.progress-step {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 6px;
		opacity: 0.4;
		transition: opacity 0.3s;
	}

	.progress-step.active,
	.progress-step.completed {
		opacity: 1;
	}

	.step-number {
		width: 32px;
		height: 32px;
		border-radius: 50%;
		background: #e5e7eb;
		color: #6b7280;
		display: flex;
		align-items: center;
		justify-content: center;
		font-weight: 600;
		font-size: 14px;
		transition: all 0.3s;
	}

	.progress-step.active .step-number {
		background: #3b82f6;
		color: white;
	}

	.progress-step.completed .step-number {
		background: #10b981;
		color: white;
	}

	.step-label {
		font-size: 12px;
		color: #6b7280;
		font-weight: 500;
	}

	.progress-step.active .step-label {
		color: #3b82f6;
		font-weight: 600;
	}

	.progress-step.completed .step-label {
		color: #10b981;
	}

	.progress-line {
		width: 40px;
		height: 2px;
		background: #e5e7eb;
		transition: background 0.3s;
	}

	.progress-line.completed {
		background: #10b981;
	}

	.loading-spinner {
		width: 16px;
		height: 16px;
		border: 2px solid rgba(255, 255, 255, 0.3);
		border-top: 2px solid white;
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}

	@media (max-width: 768px) {
		.template-content {
			width: 98%;
			max-height: 98vh;
		}
		
		.template-header {
			flex-direction: column;
			gap: 12px;
			padding: 16px;
		}
		
		.template-body {
			padding: 20px;
		}
		
		.stats-grid {
			grid-template-columns: 1fr;
		}
		
		.signature-grid {
			grid-template-columns: 1fr;
			gap: 24px;
		}
		
		.action-buttons {
			flex-direction: column;
		}
	}
</style>