<script>
	import { createEventDispatcher, onMount } from 'svelte';
	import { get } from 'svelte/store';
	import { supabase, supabaseAdmin } from '$lib/utils/supabase';
	import { currentUser, isAuthenticated } from '$lib/utils/persistentAuth';
	import { notificationManagement } from '$lib/utils/notificationManagement';
	
	export let data;
	
	const dispatch = createEventDispatcher();
	
	let isEditing = false;
	let editableWarning = data.warningText;
	let isSending = false;
	let isSaving = false;
	let sendError = null;
	let hasWhatsApp = false;
	let whatsappNumber = '';
	let warningSaved = false; // Flag to prevent duplicate saves

	// Multi-language translations
	const translations = {
		en: {
			companyName: 'AQURA MANAGEMENT SYSTEM',
			documentTitle: 'PERFORMANCE WARNING NOTICE',
			date: 'Date:',
			to: 'To:',
			from: 'From:',
			subject: 'Subject:',
			subjectText: 'Performance Improvement Required',
			performanceSummary: 'Performance Summary',
			totalTasksAssigned: 'Total Tasks Assigned:',
			tasksCompleted: 'Tasks Completed:',
			overdueTasks: 'Overdue Tasks:',
			completionRate: 'Completion Rate:',
			warningDetails: 'Warning Details',
			employeeSignature: 'Employee Signature',
			managerSignature: 'Manager Signature',
			edit: 'Edit',
			print: 'Print',
			sendWarning: 'Send Warning',
			sendWhatsApp: 'Send WhatsApp',
			notificationSent: 'Notification sent successfully!',
			whatsappSent: 'WhatsApp message sent!',
			warningSent: 'Warning sent successfully!',
			datePlaceholder: 'Date: ________________',
			improvementRequired: 'Immediate improvement is required to avoid further disciplinary action.',
			documentFooter: 'This document is generated by Aqura Management System'
		},
		hi: {
			companyName: 'अक्वरा प्रबंधन प्रणाली',
			documentTitle: 'प्रदर्शन चेतावनी सूचना',
			date: 'दिनांक:',
			to: 'को:',
			from: 'से:',
			subject: 'विषय:',
			subjectText: 'प्रदर्शन सुधार आवश्यक',
			performanceSummary: 'प्रदर्शन सारांश',
			totalTasksAssigned: 'कुल सौंपे गए कार्य:',
			tasksCompleted: 'पूर्ण किए गए कार्य:',
			overdueTasks: 'विलंबित कार्य:',
			completionRate: 'पूर्णता दर:',
			warningDetails: 'चेतावनी विवरण',
			employeeSignature: 'कर्मचारी हस्ताक्षर',
			managerSignature: 'प्रबंधक हस्ताक्षर',
			edit: 'संपादित करें',
			print: 'प्रिंट',
			save: 'चेतावनी सहेजें',
			sendWarning: 'चेतावनी भेजें',
			sendWhatsApp: 'व्हाट्सएप भेजें',
			notificationSent: 'सूचना सफलतापूर्वक भेजी गई!',
			whatsappSent: 'व्हाट्सएप संदेश भेजा गया!',
			datePlaceholder: 'दिनांक: ________________',
			improvementRequired: 'अनुशासनात्मक कार्रवाई से बचने के लिए तत्काल सुधार आवश्यक है।',
			documentFooter: 'यह दस्तावेज अक्वरा प्रबंधन प्रणाली द्वारा उत्पन्न किया गया है'
		},
		ar: {
			companyName: 'نظام إدارة أكورا',
			documentTitle: 'إشعار تحذير الأداء',
			date: 'التاريخ:',
			to: 'إلى:',
			from: 'من:',
			subject: 'الموضوع:',
			subjectText: 'تحسين الأداء مطلوب',
			performanceSummary: 'ملخص الأداء',
			totalTasksAssigned: 'إجمالي المهام المكلفة:',
			tasksCompleted: 'المهام المكتملة:',
			overdueTasks: 'المهام المتأخرة:',
			completionRate: 'معدل الإنجاز:',
			warningDetails: 'تفاصيل التحذير',
			employeeSignature: 'توقيع الموظف',
			managerSignature: 'توقيع المدير',
			edit: 'تعديل',
			print: 'طباعة',
			save: 'حفظ التحذير',
			sendWarning: 'إرسال تحذير',
			sendWhatsApp: 'إرسال واتساب',
			notificationSent: 'تم إرسال الإشعار بنجاح!',
			whatsappSent: 'تم إرسال رسالة واتساب!',
			datePlaceholder: 'التاريخ: ________________',
			improvementRequired: 'التحسن الفوري مطلوب لتجنب اتخاذ إجراءات تأديبية إضافية.',
			documentFooter: 'تم إنشاء هذا المستند بواسطة نظام إدارة أكورا'
		},
		ur: {
			companyName: 'اکورا منیجمنٹ سسٹم',
			documentTitle: 'کارکردگی انتباہی نوٹس',
			date: 'تاریخ:',
			to: 'کو:',
			from: 'سے:',
			subject: 'موضوع:',
			subjectText: 'کارکردگی میں بہتری درکار',
			performanceSummary: 'کارکردگی کا خلاصہ',
			totalTasksAssigned: 'کل تفویض شدہ کام:',
			tasksCompleted: 'مکمل شدہ کام:',
			overdueTasks: 'تاخیر سے کام:',
			completionRate: 'تکمیل کی شرح:',
			warningDetails: 'انتباہ کی تفصیلات',
			employeeSignature: 'ملازم کے دستخط',
			managerSignature: 'منیجر کے دستخط',
			edit: 'ترمیم',
			print: 'پرنٹ',
			sendWarning: 'انتباہ بھیجیں',
			sendWhatsApp: 'واٹس ایپ بھیجیں',
			notificationSent: 'اطلاع کامیابی سے بھیج دی گئی!',
			whatsappSent: 'واٹس ایپ پیغام بھیج دیا گیا!',
			datePlaceholder: 'تاریخ: ________________',
			improvementRequired: 'مزید تادیبی کارروائی سے بچنے کے لیے فوری بہتری درکار ہے۔',
			documentFooter: 'یہ دستاویز اکورا منیجمنٹ سسٹم کے ذریعے تیار کی گئی ہے'
		},
		ta: {
			companyName: 'அக்வரா மேலாண்மை அமைப்பு',
			documentTitle: 'செயல்திறன் எச்சரிக்கை அறிவிப்பு',
			date: 'தேதி:',
			to: 'பெறுநர்:',
			from: 'அனுப்புநர்:',
			subject: 'விषயம்:',
			subjectText: 'செயல்திறன் மேம்பாடு தேவை',
			performanceSummary: 'செயல்திறன் சுருக்கம்',
			totalTasksAssigned: 'மொத்த ஒதுக்கப்பட்ட பணிகள்:',
			tasksCompleted: 'நிறைவேற்றப்பட்ட பணிகள்:',
			overdueTasks: 'தாமதமான பணிகள்:',
			completionRate: 'நிறைவேற்றல் விகிதம்:',
			warningDetails: 'எச்சரிக்கை விவரங்கள்',
			employeeSignature: 'ஊழியர் கையொப்பம்',
			managerSignature: 'மேலாளர் கையொப்பம்',
			edit: 'திருத்து',
			print: 'அச்சிடு',
			sendWarning: 'எச்சரிக்கை அனுப்பு',
			sendWhatsApp: 'வாட்ஸ்அப் அனுப்பு',
			notificationSent: 'அறிவிப்பு வெற்றிகரமாக அனுப்பப்பட்டது!',
			whatsappSent: 'வாட்ஸ்அப் செய்தி அனுப்பப்பட்டது!',
			datePlaceholder: 'தேதி: ________________',
			improvementRequired: 'மேலும் ஒழுங்குமுறை நடவடிக்கையைத் தவிர்க்க உடனடி முன்னேற்றம் தேவை.',
			documentFooter: 'இந்த ஆவணம் அக்வரா மேலாண்மை அமைப்பால் உருவாக்கப்பட்டது'
		},
		ml: {
			companyName: 'അക്വാറ മാനേജ്‌മെന്റ് സിസ്റ്റം',
			documentTitle: 'പ്രകടന മുന്നറിയിപ്പ് അറിയിപ്പ്',
			date: 'തീയതി:',
			to: 'വേണ്ടി:',
			from: 'നിന്ന്:',
			subject: 'വിഷയം:',
			subjectText: 'പ്രകടന മെച്ചപ്പെടുത്തൽ ആവശ്യം',
			performanceSummary: 'പ്രകടന സംഗ്രഹം',
			totalTasksAssigned: 'മൊത്തം നിയോഗിച്ച ജോലികൾ:',
			tasksCompleted: 'പൂർത്തീകരിച്ച ജോലികൾ:',
			overdueTasks: 'കാലഹരണപ്പെട്ട ജോലികൾ:',
			completionRate: 'പൂർത്തീകരണ നിരക്ക്:',
			warningDetails: 'മുന്നറിയിപ്പ് വിശദാംശങ്ങൾ',
			employeeSignature: 'ജീവനക്കാരന്റെ ഒപ്പ്',
			managerSignature: 'മാനേജറുടെ ഒപ്പ്',
			edit: 'എഡിറ്റ്',
			print: 'പ്രിന്റ്',
			sendWarning: 'മുന്നറിയിപ്പ് അയയ്ക്കുക',
			sendWhatsApp: 'വാട്സ്ആപ്പ് അയയ്ക്കുക',
			notificationSent: 'അറിയിപ്പ് വിജയകരമായി അയച്ചു!',
			whatsappSent: 'വാട്സ്ആപ്പ് സന്ദേശം അയച്ചു!',
			datePlaceholder: 'തീയതി: ________________',
			improvementRequired: 'കൂടുതൽ അച്ചടക്ക നടപടികൾ ഒഴിവാക്കാൻ ഉടനടി മെച്ചപ്പെടുത്തൽ ആവശ്യമാണ്.',
			documentFooter: 'ഈ ഡോക്യുമെന്റ് അക്വാറ മാനേജ്‌മെന്റ് സിസ്റ്റം സൃഷ്ടിച്ചതാണ്'
		},
		bn: {
			companyName: 'আকুরা ম্যানেজমেন্ট সিস্টেম',
			documentTitle: 'কর্মক্ষমতা সতর্কতা নোটিশ',
			date: 'তারিখ:',
			to: 'প্রতি:',
			from: 'হতে:',
			subject: 'বিষয়:',
			subjectText: 'কর্মক্ষমতা উন্নতি প্রয়োজন',
			performanceSummary: 'কর্মক্ষমতা সারসংক্ষেপ',
			totalTasksAssigned: 'মোট নিযুক্ত কাজ:',
			tasksCompleted: 'সম্পন্ন কাজ:',
			overdueTasks: 'বিলম্বিত কাজ:',
			completionRate: 'সমাপ্তির হার:',
			warningDetails: 'সতর্কতার বিশদ',
			employeeSignature: 'কর্মচারীর স্বাক্ষর',
			managerSignature: 'ম্যানেজারের স্বাক্ষর',
			edit: 'সম্পাদনা',
			print: 'মুদ্রণ',
			sendWarning: 'সতর্কতা পাঠান',
			sendWhatsApp: 'হোয়াটসঅ্যাপ পাঠান',
			notificationSent: 'বিজ্ঞপ্তি সফলভাবে পাঠানো হয়েছে!',
			whatsappSent: 'হোয়াটসঅ্যাপ বার্তা পাঠানো হয়েছে!',
			datePlaceholder: 'তারিখ: ________________',
			improvementRequired: 'আরও শাস্তিমূলক ব্যবস্থা এড়াতে তাৎক্ষণিক উন্নতি প্রয়োজন।',
			documentFooter: 'এই নথিটি আকুরা ম্যানেজমেন্ট সিস্টেম দ্বারা তৈরি'
		}
	};

	// Get current language translations
	$: t = translations[data.language] || translations.en;

	// Check if user has WhatsApp contact
	onMount(async () => {
		await checkWhatsAppContact();
	});

	async function checkWhatsAppContact() {
		try {
			let userData = null;
			let userError = null;

			// First try to get user by username if available
			if (data.recipientUsername && data.recipientUsername !== 'Unknown') {
				const result = await supabase
					.from('users')
					.select('employee_id, username')
					.eq('username', data.recipientUsername)
					.single();
				
				userData = result.data;
				userError = result.error;
			}

			// If username lookup failed or no username, try by user ID
			if ((!userData || userError) && data.recipientUserId) {
				console.log('Trying user lookup by ID:', data.recipientUserId);
				const result = await supabase
					.from('users')
					.select('employee_id, username')
					.eq('id', data.recipientUserId)
					.single();
				
				userData = result.data;
				userError = result.error;
			}

			if (userError || !userData?.employee_id) {
				console.log('No employee_id found for user:', data.recipientUsername, 'or user ID:', data.recipientUserId);
				return;
			}

			// Then get the employee's contact information
			const { data: contactData, error } = await supabase
				.from('hr_employee_contacts')
				.select('whatsapp_number')
				.eq('employee_id', userData.employee_id)
				.single();

			if (contactData && contactData.whatsapp_number) {
				hasWhatsApp = true;
				whatsappNumber = contactData.whatsapp_number;
			}
		} catch (err) {
			console.error('Error checking WhatsApp contact:', err);
		}
	}

	function toggleEdit() {
		if (isEditing) {
			// Save changes
			data.warningText = editableWarning;
		}
		isEditing = !isEditing;
	}

	// Function to lookup user ID by username
	async function lookupUserIdByUsername(username) {
		try {
			console.log(`Looking up user ID for username: ${username}`);
			
			// First try the users table
			const { data: userData, error: userError } = await supabaseAdmin
				.from('users')
				.select('id')
				.eq('username', username)
				.single();

			if (userData && !userError) {
				console.log(`Found user ID ${userData.id} for username ${username}`);
				return userData.id;
			}

			// If not found in users table, try hr_employees table
			const { data: hrData, error: hrError } = await supabaseAdmin
				.from('hr_employees')
				.select('id')
				.eq('username', username)
				.single();

			if (hrData && !hrError) {
				console.log(`Found employee ID ${hrData.id} for username ${username}`);
				return hrData.id;
			}

			console.warn(`No user ID found for username: ${username}`);
			return null;
		} catch (error) {
			console.error(`Error looking up user ID for username ${username}:`, error);
			return null;
		}
	}

	async function sendInternalNotification() {
		isSending = true;
		sendError = null;

		try {
			// Only save if not already saved
			if (!warningSaved) {
				await saveWarningRecord();
			}

			// Determine the target user ID - try multiple possible fields
			let targetUserId = data.recipientUserId || 
							   data.assignmentData?.assigned_to_user_id || 
							   data.assignmentData?.assignedToUserId ||
							   data.assignmentData?.user_id ||
							   data.assignmentData?.userId;

			if (!targetUserId) {
				// If we still don't have a user ID, try to look it up by username
				const username = data.recipientUsername || data.assignmentData?.assigned_to_username || data.assignmentData?.assigned_to;
				if (username) {
					console.warn(`No user ID found for notification target. Attempting to look up user ID for username: ${username}`);
					targetUserId = await lookupUserIdByUsername(username);
					
					if (!targetUserId) {
						throw new Error(`No valid user ID found for notification target "${username}". User ID is required for push notifications.`);
					}
				} else {
					throw new Error('No valid user ID or username found for notification target');
				}
			}

			// Create notification using notificationManagement for proper push notification support
			const notificationData = {
				title: 'Performance Warning',
				message: `Warning: Performance Review Required\n\n${editableWarning}`,
				type: 'warning',
				priority: 'high',
				target_type: 'specific_users',
				target_users: [targetUserId]
			};

			// Use assigned_by or current user for createdBy - handle undefined case
			const createdBy = data.assignedBy || 
							  data.assignmentData?.assigned_by || 
							  'System Administrator';

			await notificationManagement.createNotification(notificationData, createdBy);

			alert('Warning notification sent successfully with push notification!');
			dispatch('close');
		} catch (err) {
			console.error('Error sending notification:', err);
			sendError = 'Failed to send notification: ' + err.message;
		} finally {
			isSending = false;
		}
	}

	async function saveWarningRecord() {
		if (warningSaved) {
			console.log('Warning already saved, skipping duplicate save');
			return;
		}

		try {
			// Get current user information from persistent auth
			const user = get(currentUser);
			
			if (!user) {
				throw new Error('User not authenticated');
			}

			// Get the employee information from the user_id to properly link the employee
			let employeeId = null;
			let actualUsername = null;
			let actualUserId = null;
			
			// First try to get user ID from data, then lookup by username if needed
			actualUserId = data.recipientUserId || 
						   data.assignmentData?.assigned_to_user_id || 
						   data.assignmentData?.assignedToUserId;
			
			if (!actualUserId) {
				// Try to lookup user ID by username
				const username = data.recipientUsername || data.assignmentData?.assigned_to_username || data.assignmentData?.assigned_to;
				if (username) {
					actualUserId = await lookupUserIdByUsername(username);
				}
			}
			
			if (actualUserId) {
				try {
					// Get user details to find linked employee
					const { data: userDetails, error: userError } = await supabaseAdmin
						.from('users')
						.select(`
							id,
							username,
							employee_id,
							hr_employees(id, name, employee_id)
						`)
						.eq('id', actualUserId)
						.single();
					
					if (!userError && userDetails) {
						actualUsername = userDetails.username;
						employeeId = userDetails.employee_id; // This is the UUID from users.employee_id
						console.log('Found user details:', {
							userId: userDetails.id,
							username: userDetails.username,
							employeeId: userDetails.employee_id,
							employeeData: userDetails.hr_employees
						});
					} else {
						console.warn('Could not find user details for ID:', targetUserId);
					}
				} catch (err) {
					console.error('Error fetching user details:', err);
				}
			}

			// Prepare warning record data matching the database schema
			const warningRecord = {
				user_id: actualUserId, // Use the looked-up user ID
				employee_id: employeeId, // Now properly linked to hr_employees table
				username: actualUsername || data.recipientUsername || data.assignmentData?.assigned_to || 'unknown_user',
				warning_type: data.warningType,
				has_fine: data.hasFine || false,
				fine_amount: data.fineAmount || null,
				fine_currency: data.fineCurrency || 'USD',
				fine_status: data.hasFine ? 'pending' : null,
				warning_text: editableWarning,
				language_code: data.language || 'en',
				task_id: data.assignmentData?.taskId || data.assignmentData?.task_id || null,
				task_title: data.assignmentData?.taskTitle || data.assignmentData?.task_title || null,
				task_description: data.assignmentData?.taskDescription || data.assignmentData?.task_description || null,
				assignment_id: data.assignmentData?.assignmentId || data.assignmentData?.assignment_id || data.assignmentData?.id || null,
				total_tasks_assigned: data.totalAssigned || data.assignmentData?.total_assigned || 0,
				total_tasks_completed: data.totalCompleted || data.assignmentData?.total_completed || 0,
				total_tasks_overdue: data.totalOverdue || data.assignmentData?.total_overdue || 0,
				completion_rate: data.completionRate || 0,
				issued_by: user?.id || 'system',
				issued_by_username: user?.username || 'system',
				warning_status: 'active',
				branch_id: data.assignmentData?.branchId || data.assignmentData?.branch_id || null,
				severity_level: determineSeverityLevel(),
				follow_up_required: data.hasFine || data.completionRate < 50,
				follow_up_date: data.hasFine ? new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] : null // 7 days from now
			};

			console.log('Saving warning record:', warningRecord);

			// Use admin client to bypass RLS since we have custom authentication
			const { error } = await supabaseAdmin
				.from('employee_warnings')
				.insert([warningRecord]);

			if (error) {
				console.error('Database error:', error);
				throw new Error(`Failed to save warning record: ${error.message}`);
			}

			console.log('Warning record saved successfully');
			warningSaved = true; // Set flag after successful save
		} catch (err) {
			console.error('Error saving warning record:', err);
			// Don't set warningSaved flag if save failed
			throw err;
		}
	}

	function determineSeverityLevel() {
		const completionRate = data.completionRate || 0;
		const hasFine = data.hasFine || false;
		
		if (hasFine && completionRate < 30) return 'critical';
		if (hasFine || completionRate < 40) return 'high';
		if (completionRate < 60) return 'medium';
		return 'low';
	}

	async function sendWarning() {
		if (isSending || isSaving) return;
		
		isSending = true;
		sendError = '';
		
		try {
			// First save the warning record if not already saved
			if (!warningSaved) {
				await saveWarningRecord();
			}
			
			// Then send the notification
			await sendInternalNotification();
			
			// Show success message
			alert(t.warningSent || 'Warning sent successfully!');
			
			// Close modal after successful send
			dispatch('close');
			
		} catch (err) {
			console.error('Error sending warning:', err);
			sendError = 'Failed to send warning: ' + err.message;
		} finally {
			isSending = false;
		}
	}

	function sendToWhatsApp() {
		if (!hasWhatsApp || !whatsappNumber) {
			alert('WhatsApp number not available for this employee');
			return;
		}

		// Save warning record before sending WhatsApp (if not already saved)
		const savePromise = warningSaved ? Promise.resolve() : saveWarningRecord();
		
		savePromise.then(() => {
			// Generate WhatsApp message
			const message = generateWhatsAppMessage();
			const encodedMessage = encodeURIComponent(message);
			const whatsappUrl = `https://web.whatsapp.com/send?phone=${whatsappNumber}&text=${encodedMessage}`;
			
			// Open WhatsApp Web in new tab
			window.open(whatsappUrl, '_blank');
		}).catch(err => {
			console.error('Error saving warning before WhatsApp:', err);
			alert('Warning could not be saved to database, but proceeding with WhatsApp');
			
			// Still send WhatsApp even if saving fails
			const message = generateWhatsAppMessage();
			const encodedMessage = encodeURIComponent(message);
			const whatsappUrl = `https://web.whatsapp.com/send?phone=${whatsappNumber}&text=${encodedMessage}`;
			window.open(whatsappUrl, '_blank');
		});
	}

	function generateWhatsAppMessage() {
		return `*${t.documentTitle}*

${t.to} ${data.recipientName},

*${t.performanceSummary}:*
• ${t.totalTasksAssigned} ${data.totalAssigned}
• ${t.tasksCompleted} ${data.totalCompleted}
• ${t.overdueTasks} ${data.totalOverdue}
• ${t.completionRate} ${data.completionRate}%

*${t.warningDetails}:*
${editableWarning}

---
${t.from} ${data.assignedBy}
${t.date} ${new Date().toLocaleDateString()}

${t.companyName}`;
	}

	function printTemplate() {
		// Save warning record before printing (if not already saved)
		const savePromise = warningSaved ? Promise.resolve() : saveWarningRecord();
		
		savePromise.then(() => {
			const printWindow = window.open('', '_blank');
			const printContent = generatePrintableHTML();
			
			printWindow.document.write(printContent);
			printWindow.document.close();
			printWindow.print();
		}).catch(err => {
			console.error('Error saving warning before printing:', err);
			alert('Warning could not be saved to database, but proceeding with print');
			
			// Still print even if saving fails
			const printWindow = window.open('', '_blank');
			const printContent = generatePrintableHTML();
			printWindow.document.write(printContent);
			printWindow.document.close();
			printWindow.print();
		});
	}

	function generatePrintableHTML() {
		const currentDate = new Date().toLocaleDateString();
		
		return `
		<!DOCTYPE html>
		<html>
		<head>
			<title>${t.documentTitle}</title>
			<style>
				@page {
					size: A4;
					margin: 20mm;
				}
				body {
					font-family: Arial, sans-serif;
					margin: 0;
					padding: 0;
					line-height: 1.4;
					color: #333;
					font-size: 12px;
				}
				.header {
					text-align: center;
					margin-bottom: 25px;
					border-bottom: 2px solid #333;
					padding-bottom: 15px;
				}
				.logo-container {
					width: 80px;
					height: 40px;
					margin: 0 auto 12px;
					display: flex;
					align-items: center;
					justify-content: center;
				}
				.company-logo {
					max-width: 100%;
					max-height: 100%;
					object-fit: contain;
				}
				.company-name {
					font-size: 18px;
					font-weight: 700;
					color: #111827;
					margin: 0;
				}
				.document-title {
					font-size: 16px;
					font-weight: 700;
					color: #dc2626;
					margin: 12px 0 0 0;
					letter-spacing: 0.5px;
				}
				.logo-container {
					width: 80px;
					height: 40px;
					margin: 0 auto 10px;
					display: flex;
					align-items: center;
					justify-content: center;
				}
				.company-logo {
					max-width: 100%;
					max-height: 100%;
					object-fit: contain;
				}
				.company-name {
					font-size: 16px;
					font-weight: bold;
					margin: 5px 0;
				}
				.document-title {
					font-size: 14px;
					font-weight: bold;
					color: #d32f2f;
					margin: 10px 0;
				}
				.content {
					margin: 20px 0;
				}
				.warning-content {
					background: #fff3cd;
					border: 1px solid #ffeaa7;
					padding: 15px;
					margin: 15px 0;
					border-radius: 4px;
					font-size: 11px;
				}
				.statistics {
					display: grid;
					grid-template-columns: repeat(2, 1fr);
					gap: 8px;
					margin: 15px 0;
					padding: 12px;
					background: #f8f9fa;
					border-radius: 4px;
					font-size: 11px;
				}
				.stat-item {
					display: flex;
					justify-content: space-between;
				}
				.signatures {
					margin-top: 30px;
					display: grid;
					grid-template-columns: 1fr 1fr;
					gap: 20px;
					font-size: 11px;
				}
				.signature-section {
					text-align: center;
				}
				.signature-line {
					border-top: 1px solid #333;
					margin-top: 25px;
					padding-top: 5px;
				}
				.footer {
					margin-top: 20px;
					text-align: center;
					font-size: 10px;
					color: #666;
				}
				@media print {
					body { 
						margin: 0; 
						font-size: 11px;
					}
					.header {
						margin-bottom: 20px;
						padding-bottom: 10px;
					}
				}
			</style>
		</head>
		<body>
			<div class="header">
				<div class="logo-container">
					<img src="/icons/logo.png" alt="Company Logo" class="company-logo" />
				</div>
				<div class="company-name">{t.companyName}</div>
				<div class="document-title">{t.documentTitle}</div>
			</div>
			
			<div class="content">
				<p><strong>${t.date}</strong> ${currentDate}</p>
				<p><strong>${t.to}</strong> ${data.recipientName}</p>
				<p><strong>${t.from}</strong> ${data.assignedBy}</p>
				<p><strong>${t.subject}</strong> ${t.subjectText}</p>
				
				<div class="statistics">
					<div class="stat-item">
						<span>${t.totalTasksAssigned}</span>
						<span><strong>${data.totalAssigned}</strong></span>
					</div>
					<div class="stat-item">
						<span>${t.tasksCompleted}</span>
						<span><strong>${data.totalCompleted}</strong></span>
					</div>
					<div class="stat-item">
						<span>${t.overdueTasks}</span>
						<span><strong style="color: #d32f2f">${data.totalOverdue}</strong></span>
					</div>
					<div class="stat-item">
						<span>${t.completionRate}</span>
						<span><strong>${data.completionRate}%</strong></span>
					</div>
				</div>
				
				<div class="warning-content">
					${editableWarning.split('\n').slice(0, 10).map(line => `<p style="margin: 5px 0;">${line}</p>`).join('')}
				</div>
				
				<p style="margin-top: 15px; font-size: 11px;">${t.improvementRequired}</p>
			</div>
			
			<div class="signatures">
				<div class="signature-section">
					<div class="signature-line">
						<strong>${t.managerSignature}</strong><br>
						${t.datePlaceholder}<br>
						Signature: ________________
					</div>
				</div>
				<div class="signature-section">
					<div class="signature-line">
						<strong>${t.employeeSignature}</strong><br>
						${t.datePlaceholder}<br>
						Signature: ________________
					</div>
				</div>
			</div>
			
			<div class="footer">
				<p>${t.documentFooter}</p>
			</div>
		</body>
		</html>`;
	}

	function closeModal() {
		dispatch('close');
	}
</script>

<div class="template-overlay" on:click={closeModal}>
	<div class="template-content" on:click|stopPropagation>
		<div class="template-header">
			<div class="header-left">
				<h2 class="template-title">Warning Template</h2>
				<span class="language-badge">{data.language.toUpperCase()}</span>
			</div>
			<div class="header-right">
				<button class="edit-btn" on:click={toggleEdit}>
					{#if isEditing}
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
						</svg>
						Save
					{:else}
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"/>
						</svg>
						{t.edit}
					{/if}
				</button>
				<button class="print-btn" on:click={printTemplate}>
					<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/>
					</svg>
					{t.print}
				</button>
				<button class="close-btn" on:click={closeModal}>
					<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
					</svg>
				</button>
			</div>
		</div>

		<div class="template-body">
			<!-- Template Header Section -->
			<div class="document-header">
				<div class="logo-section">
					<div class="logo-container">
						<img src="/icons/logo.png" alt="Company Logo" class="company-logo" />
					</div>
					<h3 class="company-name">{t.companyName}</h3>
				</div>
				<h2 class="document-title">{t.documentTitle}</h2>
			</div>

			<!-- Document Details -->
			<div class="document-details">
				<div class="detail-row">
					<span class="detail-label">{t.date}</span>
					<span class="detail-value">{new Date().toLocaleDateString()}</span>
				</div>
				<div class="detail-row">
					<span class="detail-label">{t.to}</span>
					<span class="detail-value">{data.recipientName} ({data.recipientUsername})</span>
				</div>
				<div class="detail-row">
					<span class="detail-label">{t.from}</span>
					<span class="detail-value">{data.assignedBy}</span>
				</div>
				<div class="detail-row">
					<span class="detail-label">{t.subject}</span>
					<span class="detail-value">{t.subjectText}</span>
				</div>
			</div>

			<!-- Performance Statistics -->
			<div class="statistics-section">
				<h4 class="section-title">{t.performanceSummary}</h4>
				<div class="stats-grid">
					<div class="stat-item">
						<span class="stat-label">{t.totalTasksAssigned}</span>
						<span class="stat-value">{data.totalAssigned}</span>
					</div>
					<div class="stat-item">
						<span class="stat-label">{t.tasksCompleted}</span>
						<span class="stat-value stat-completed">{data.totalCompleted}</span>
					</div>
					<div class="stat-item">
						<span class="stat-label">{t.overdueTasks}</span>
						<span class="stat-value stat-overdue">{data.totalOverdue}</span>
					</div>
					<div class="stat-item">
						<span class="stat-label">{t.completionRate}</span>
						<span class="stat-value">{data.completionRate}%</span>
					</div>
				</div>
			</div>

			<!-- Warning Content -->
			<div class="warning-section">
				<h4 class="section-title">{t.warningDetails}</h4>
				{#if isEditing}
					<textarea 
						bind:value={editableWarning}
						class="warning-textarea"
						rows="8"
						placeholder="Enter warning text..."
					></textarea>
				{:else}
					<div class="warning-text">
						{#each editableWarning.split('\n') as line}
							<p>{line}</p>
						{/each}
					</div>
				{/if}
			</div>

			<!-- Signature Section -->
			<div class="signature-section">
				<div class="signature-grid">
					<div class="signature-box">
						<h5 class="signature-title">{t.managerSignature}</h5>
						<div class="signature-line">
							<span>Name: ________________</span>
						</div>
						<div class="signature-line">
							<span>{t.datePlaceholder}</span>
						</div>
						<div class="signature-line">
							<span>Signature: ________________</span>
						</div>
					</div>
					<div class="signature-box">
						<h5 class="signature-title">{t.employeeSignature}</h5>
						<div class="signature-line">
							<span>Name: {data.recipientName}</span>
						</div>
						<div class="signature-line">
							<span>{t.datePlaceholder}</span>
						</div>
						<div class="signature-line">
							<span>Signature: ________________</span>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Error Message -->
		{#if sendError}
			<div class="error-message">
				{sendError}
			</div>
		{/if}

		<!-- Action Buttons -->
		<div class="template-footer">
			<div class="action-buttons">
				<button 
					class="action-btn notification-btn"
					on:click={sendWarning}
					disabled={isSending || isSaving}
				>
					{#if isSending || isSaving}
						<div class="loading-spinner"></div>
					{:else}
						<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"/>
						</svg>
					{/if}
					{t.sendWarning}
				</button>
				
				{#if hasWhatsApp}
					<button 
						class="action-btn whatsapp-btn"
						on:click={sendToWhatsApp}
					>
						<svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
							<path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893A11.821 11.821 0 0020.885 3.106"/>
						</svg>
						{t.sendWhatsApp}
					</button>
				{/if}
			</div>
		</div>
	</div>
</div>

<style>
	.template-overlay {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background: rgba(0, 0, 0, 0.6);
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1001;
	}

	.template-content {
		background: white;
		border-radius: 12px;
		box-shadow: 0 25px 50px rgba(0, 0, 0, 0.15);
		width: 95%;
		max-width: 900px;
		max-height: 95vh;
		overflow-y: auto;
		position: relative;
	}

	.template-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 20px 24px;
		border-bottom: 1px solid #e5e7eb;
		position: sticky;
		top: 0;
		background: white;
		z-index: 10;
	}

	.header-left {
		display: flex;
		align-items: center;
		gap: 12px;
	}

	.template-title {
		font-size: 20px;
		font-weight: 600;
		color: #111827;
		margin: 0;
	}

	.language-badge {
		background: #3b82f6;
		color: white;
		padding: 4px 8px;
		border-radius: 4px;
		font-size: 12px;
		font-weight: 600;
	}

	.header-right {
		display: flex;
		align-items: center;
		gap: 8px;
	}

	.edit-btn, .print-btn, .close-btn {
		display: flex;
		align-items: center;
		gap: 4px;
		padding: 6px 12px;
		border: 1px solid #d1d5db;
		background: white;
		color: #374151;
		border-radius: 6px;
		font-size: 14px;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.edit-btn:hover, .print-btn:hover {
		background: #f9fafb;
		border-color: #9ca3af;
	}

	.close-btn {
		border-color: transparent;
		color: #6b7280;
	}

	.close-btn:hover {
		background: #f3f4f6;
		color: #374151;
	}

	.template-body {
		padding: 20px;
		max-width: 210mm;
		min-height: 297mm;
		margin: 0 auto;
		background: white;
		box-shadow: 0 0 10px rgba(0,0,0,0.1);
	}

	.document-header {
		text-align: center;
		margin-bottom: 20px;
		padding-bottom: 15px;
		border-bottom: 2px solid #111827;
	}

	.logo-section {
		margin-bottom: 20px;
	}

	.logo-placeholder {
		width: 120px;
		height: 60px;
		background: #f3f4f6;
		border: 2px dashed #9ca3af;
		margin: 0 auto 16px;
		display: flex;
		align-items: center;
		justify-content: center;
		color: #6b7280;
		font-size: 12px;
		font-weight: 600;
		border-radius: 8px;
	}

	.logo-container {
		width: 80px;
		height: 40px;
		margin: 0 auto 12px;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.company-logo {
		max-width: 100%;
		max-height: 100%;
		object-fit: contain;
	}

	.company-name {
		font-size: 18px;
		font-weight: 700;
		color: #111827;
		margin: 0;
	}

	.document-title {
		font-size: 16px;
		font-weight: 700;
		color: #dc2626;
		margin: 12px 0 0 0;
		letter-spacing: 0.5px;
	}

	.document-details {
		margin-bottom: 24px;
		padding: 20px;
		background: #f9fafb;
		border-radius: 8px;
	}

	.detail-row {
		display: flex;
		margin-bottom: 8px;
	}

	.detail-row:last-child {
		margin-bottom: 0;
	}

	.detail-label {
		font-weight: 600;
		color: #374151;
		min-width: 80px;
	}

	.detail-value {
		color: #111827;
	}

	.statistics-section, .warning-section, .signature-section {
		margin-bottom: 32px;
	}

	.section-title {
		font-size: 18px;
		font-weight: 600;
		color: #111827;
		margin: 0 0 16px 0;
		padding-bottom: 8px;
		border-bottom: 1px solid #e5e7eb;
	}

	.stats-grid {
		display: grid;
		grid-template-columns: repeat(2, 1fr);
		gap: 16px;
		padding: 20px;
		background: #f8fafc;
		border-radius: 8px;
		border: 1px solid #e2e8f0;
	}

	.stat-item {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.stat-label {
		font-weight: 500;
		color: #475569;
	}

	.stat-value {
		font-weight: 700;
		color: #111827;
	}

	.stat-completed {
		color: #059669;
	}

	.stat-overdue {
		color: #dc2626;
	}

	.warning-textarea {
		width: 100%;
		padding: 16px;
		border: 1px solid #d1d5db;
		border-radius: 8px;
		font-size: 14px;
		line-height: 1.6;
		resize: vertical;
		min-height: 200px;
	}

	.warning-textarea:focus {
		outline: none;
		border-color: #3b82f6;
		box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
	}

	.warning-text {
		padding: 20px;
		background: #fff3cd;
		border: 1px solid #ffeaa7;
		border-radius: 8px;
		line-height: 1.6;
	}

	.warning-text p {
		margin: 0 0 12px 0;
		color: #111827;
	}

	.warning-text p:last-child {
		margin-bottom: 0;
	}

	.signature-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 40px;
	}

	.signature-box {
		text-align: center;
	}

	.signature-title {
		font-size: 16px;
		font-weight: 600;
		color: #111827;
		margin: 0 0 20px 0;
	}

	.signature-line {
		margin-bottom: 16px;
		padding-top: 8px;
		border-top: 1px solid #9ca3af;
		font-size: 14px;
		color: #374151;
	}

	.error-message {
		background: #fef2f2;
		border: 1px solid #fecaca;
		color: #dc2626;
		padding: 16px;
		margin: 16px 24px;
		border-radius: 8px;
		font-size: 14px;
	}

	.template-footer {
		padding: 24px;
		border-top: 1px solid #e5e7eb;
		background: #f9fafb;
		border-bottom-left-radius: 12px;
		border-bottom-right-radius: 12px;
	}

	.action-buttons {
		display: flex;
		gap: 12px;
		justify-content: center;
		flex-wrap: wrap;
	}

	.action-btn {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 12px 20px;
		border: none;
		border-radius: 8px;
		font-size: 14px;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s ease;
	}

	.notification-btn {
		background: #3b82f6;
		color: white;
	}

	.notification-btn:hover:not(:disabled) {
		background: #2563eb;
	}

	.notification-btn:disabled {
		opacity: 0.6;
		cursor: not-allowed;
	}

	.whatsapp-btn {
		background: #25d366;
		color: white;
	}

	.whatsapp-btn:hover {
		background: #20ba5a;
	}

	.loading-spinner {
		width: 16px;
		height: 16px;
		border: 2px solid rgba(255, 255, 255, 0.3);
		border-top: 2px solid white;
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}

	@media (max-width: 768px) {
		.template-content {
			width: 98%;
			max-height: 98vh;
		}
		
		.template-header {
			flex-direction: column;
			gap: 12px;
			padding: 16px;
		}
		
		.template-body {
			padding: 20px;
		}
		
		.stats-grid {
			grid-template-columns: 1fr;
		}
		
		.signature-grid {
			grid-template-columns: 1fr;
			gap: 24px;
		}
		
		.action-buttons {
			flex-direction: column;
		}
	}
</style>