-- Branches Table Schema
CREATE TABLE IF NOT EXISTS branches (
  id BIGINT PRIMARY KEY DEFAULT nextval('branches_id_seq'),
  name_en VARCHAR NOT NULL,
  name_ar VARCHAR NOT NULL,
  location_en VARCHAR NOT NULL,
  location_ar VARCHAR NOT NULL,
  is_active BOOLEAN DEFAULT true,
  is_main_branch BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_by BIGINT,
  updated_by BIGINT,
  vat_number VARCHAR,
  delivery_service_enabled BOOLEAN NOT NULL DEFAULT true,
  pickup_service_enabled BOOLEAN NOT NULL DEFAULT true,
  minimum_order_amount NUMERIC DEFAULT 15.00,
  is_24_hours BOOLEAN DEFAULT true,
  operating_start_time TIME WITHOUT TIME ZONE,
  operating_end_time TIME WITHOUT TIME ZONE,
  delivery_message_ar TEXT,
  delivery_message_en TEXT,
  delivery_is_24_hours BOOLEAN DEFAULT true,
  delivery_start_time TIME WITHOUT TIME ZONE,
  delivery_end_time TIME WITHOUT TIME ZONE,
  pickup_is_24_hours BOOLEAN DEFAULT true,
  pickup_start_time TIME WITHOUT TIME ZONE,
  pickup_end_time TIME WITHOUT TIME ZONE
);
