-- Order Items Table Schema
CREATE TABLE IF NOT EXISTS order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL,
  product_id VARCHAR NOT NULL,
  product_name_ar VARCHAR NOT NULL,
  product_name_en VARCHAR NOT NULL,
  product_sku VARCHAR,
  unit_id VARCHAR,
  unit_name_ar VARCHAR,
  unit_name_en VARCHAR,
  unit_size VARCHAR,
  quantity INTEGER NOT NULL,
  unit_price NUMERIC NOT NULL,
  original_price NUMERIC NOT NULL,
  discount_amount NUMERIC NOT NULL DEFAULT 0,
  final_price NUMERIC NOT NULL,
  line_total NUMERIC NOT NULL,
  has_offer BOOLEAN NOT NULL DEFAULT false,
  offer_id INTEGER,
  offer_name_ar VARCHAR,
  offer_name_en VARCHAR,
  offer_type VARCHAR,
  offer_discount_percentage NUMERIC,
  offer_special_price NUMERIC,
  item_type VARCHAR NOT NULL DEFAULT 'regular',
  bundle_id UUID,
  bundle_name_ar VARCHAR,
  bundle_name_en VARCHAR,
  is_bundle_item BOOLEAN NOT NULL DEFAULT false,
  is_bogo_free BOOLEAN NOT NULL DEFAULT false,
  bogo_group_id UUID,
  tax_rate NUMERIC NOT NULL DEFAULT 0,
  tax_amount NUMERIC NOT NULL DEFAULT 0,
  item_notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
