-- Products Table Schema
CREATE TABLE IF NOT EXISTS products (
  id VARCHAR PRIMARY KEY,
  barcode TEXT NOT NULL,
  product_name_en TEXT,
  product_name_ar TEXT,
  image_url TEXT,
  category_id VARCHAR,
  unit_id VARCHAR,
  unit_qty NUMERIC NOT NULL DEFAULT 1,
  sale_price NUMERIC NOT NULL DEFAULT 0,
  cost NUMERIC NOT NULL DEFAULT 0,
  profit NUMERIC NOT NULL DEFAULT 0,
  profit_percentage NUMERIC NOT NULL DEFAULT 0,
  current_stock INTEGER NOT NULL DEFAULT 0,
  minim_qty INTEGER NOT NULL DEFAULT 0,
  minimum_qty_alert INTEGER NOT NULL DEFAULT 0,
  maximum_qty INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  is_customer_product BOOLEAN DEFAULT true,
  is_variation BOOLEAN NOT NULL DEFAULT false,
  parent_product_barcode TEXT,
  variation_group_name_en TEXT,
  variation_group_name_ar TEXT,
  variation_order INTEGER DEFAULT 0,
  variation_image_override TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_by UUID,
  modified_by UUID,
  modified_at TIMESTAMP WITH TIME ZONE
);
