-- Users Table Schema
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  username VARCHAR NOT NULL,
  password_hash VARCHAR NOT NULL,
  salt VARCHAR NOT NULL,
  quick_access_code VARCHAR NOT NULL,
  quick_access_salt VARCHAR NOT NULL,
  user_type USER_TYPE_ENUM NOT NULL DEFAULT 'branch_specific',
  employee_id UUID,
  branch_id BIGINT,
  position_id UUID,
  avatar TEXT,
  avatar_small_url TEXT,
  avatar_medium_url TEXT,
  avatar_large_url TEXT,
  is_first_login BOOLEAN DEFAULT true,
  failed_login_attempts INTEGER DEFAULT 0,
  locked_at TIMESTAMP WITH TIME ZONE,
  locked_by UUID,
  last_login_at TIMESTAMP WITH TIME ZONE,
  password_expires_at TIMESTAMP WITH TIME ZONE,
  last_password_change TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_by BIGINT,
  updated_by BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  status VARCHAR NOT NULL DEFAULT 'active',
  ai_translation_enabled BOOLEAN NOT NULL DEFAULT false,
  is_master_admin BOOLEAN DEFAULT false,
  is_admin BOOLEAN DEFAULT false
);
