-- Notifications Table Schema
CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title VARCHAR NOT NULL,
  message TEXT NOT NULL,
  created_by VARCHAR NOT NULL DEFAULT 'system',
  created_by_name VARCHAR NOT NULL DEFAULT 'System',
  created_by_role VARCHAR NOT NULL DEFAULT 'Admin',
  target_users JSONB,
  target_roles JSONB,
  target_branches JSONB,
  scheduled_for TIMESTAMP WITH TIME ZONE,
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  expires_at TIMESTAMP WITH TIME ZONE,
  has_attachments BOOLEAN NOT NULL DEFAULT false,
  read_count INTEGER NOT NULL DEFAULT 0,
  total_recipients INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  deleted_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB,
  task_id UUID,
  task_assignment_id UUID,
  priority VARCHAR NOT NULL DEFAULT 'medium',
  status VARCHAR NOT NULL DEFAULT 'published',
  target_type VARCHAR NOT NULL DEFAULT 'all_users',
  type VARCHAR NOT NULL DEFAULT 'info'
);
