-- Expense Requisitions Table Schema
CREATE TABLE IF NOT EXISTS expense_requisitions (
  id BIGINT PRIMARY KEY DEFAULT nextval('expense_requisitions_id_seq'),
  requisition_number TEXT NOT NULL,
  branch_id BIGINT NOT NULL,
  branch_name TEXT NOT NULL,
  approver_id UUID,
  approver_name TEXT,
  expense_category_id BIGINT,
  expense_category_name_en TEXT,
  expense_category_name_ar TEXT,
  requester_id TEXT NOT NULL,
  requester_name TEXT NOT NULL,
  requester_contact TEXT NOT NULL,
  vat_applicable BOOLEAN DEFAULT false,
  amount NUMERIC NOT NULL,
  payment_category TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending',
  image_url TEXT,
  created_by UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  credit_period INTEGER,
  bank_name TEXT,
  iban TEXT,
  used_amount NUMERIC DEFAULT 0,
  remaining_balance NUMERIC DEFAULT 0,
  requester_ref_id UUID,
  is_active BOOLEAN NOT NULL DEFAULT true,
  due_date DATE,
  internal_user_id UUID,
  request_type TEXT DEFAULT 'external'
);
