-- Receiving Records Table Schema
CREATE TABLE IF NOT EXISTS receiving_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  branch_id INTEGER NOT NULL,
  vendor_id INTEGER NOT NULL,
  bill_date DATE NOT NULL,
  bill_amount NUMERIC NOT NULL,
  bill_number VARCHAR,
  payment_method VARCHAR,
  credit_period INTEGER,
  due_date DATE,
  bank_name VARCHAR,
  iban VARCHAR,
  vendor_vat_number VARCHAR,
  bill_vat_number VARCHAR,
  vat_numbers_match BOOLEAN,
  vat_mismatch_reason TEXT,
  branch_manager_user_id UUID,
  shelf_stocker_user_ids UUID[],
  accountant_user_id UUID,
  purchasing_manager_user_id UUID,
  expired_return_amount NUMERIC DEFAULT 0,
  near_expiry_return_amount NUMERIC DEFAULT 0,
  over_stock_return_amount NUMERIC DEFAULT 0,
  damage_return_amount NUMERIC DEFAULT 0,
  total_return_amount NUMERIC DEFAULT 0,
  final_bill_amount NUMERIC DEFAULT 0,
  has_expired_returns BOOLEAN DEFAULT false,
  has_near_expiry_returns BOOLEAN DEFAULT false,
  has_over_stock_returns BOOLEAN DEFAULT false,
  has_damage_returns BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  inventory_manager_user_id UUID,
  night_supervisor_user_ids UUID[],
  warehouse_handler_user_ids UUID[],
  certificate_url TEXT,
  certificate_generated_at TIMESTAMP WITH TIME ZONE,
  certificate_file_name TEXT,
  original_bill_url TEXT,
  erp_purchase_invoice_reference VARCHAR,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  pr_excel_file_url TEXT,
  erp_purchase_invoice_uploaded BOOLEAN DEFAULT false,
  pr_excel_file_uploaded BOOLEAN DEFAULT false,
  original_bill_uploaded BOOLEAN DEFAULT false
);
