-- HR Employee Documents Table Schema
CREATE TABLE IF NOT EXISTS hr_employee_documents (
  id UUID PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  employee_id UUID NOT NULL,
  document_type VARCHAR NOT NULL,
  document_name VARCHAR NOT NULL,
  file_path TEXT NOT NULL,
  file_type VARCHAR,
  expiry_date DATE,
  upload_date DATE NOT NULL DEFAULT CURRENT_DATE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  document_number VARCHAR,
  document_description TEXT,
  health_card_number VARCHAR,
  health_card_expiry DATE,
  resident_id_number VARCHAR,
  resident_id_expiry DATE,
  passport_number VARCHAR,
  passport_expiry DATE,
  driving_license_number VARCHAR,
  driving_license_expiry DATE,
  resume_uploaded BOOLEAN DEFAULT false,
  document_category DOCUMENT_CATEGORY_ENUM DEFAULT 'other',
  category_start_date DATE,
  category_end_date DATE,
  category_days INTEGER,
  category_last_working_day DATE,
  category_reason TEXT,
  category_details TEXT,
  category_content TEXT
);
