-- Non Approved Payment Scheduler Table Schema
CREATE TABLE IF NOT EXISTS non_approved_payment_scheduler (
  id BIGINT PRIMARY KEY DEFAULT nextval('non_approved_payment_scheduler_id_seq'),
  schedule_type TEXT NOT NULL,
  branch_id BIGINT NOT NULL,
  branch_name TEXT NOT NULL,
  expense_category_id BIGINT NOT NULL,
  expense_category_name_en TEXT,
  expense_category_name_ar TEXT,
  co_user_id UUID,
  co_user_name TEXT,
  bill_type TEXT,
  bill_number TEXT,
  bill_date DATE,
  payment_method TEXT,
  due_date DATE,
  credit_period INTEGER,
  amount NUMERIC NOT NULL,
  bill_file_url TEXT,
  bank_name TEXT,
  iban TEXT,
  description TEXT,
  notes TEXT,
  recurring_type TEXT,
  recurring_metadata JSONB,
  approver_id UUID NOT NULL,
  approver_name TEXT NOT NULL,
  approval_status TEXT DEFAULT 'pending',
  approved_at TIMESTAMP WITH TIME ZONE,
  approved_by UUID,
  rejection_reason TEXT,
  expense_scheduler_id BIGINT,
  created_by UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_by UUID,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
