-- =====================================================
-- SUPABASE STORAGE AND DATABASE INFORMATION REFERENCE
-- =====================================================
-- This file contains a snapshot of storage buckets and database tables
-- Fetched on: 2025-10-27T10:46:43.156Z
-- Supabase URL: https://vmypotfsyrvuublyddyt.supabase.co
-- 
-- NOTE: This is a reference file only. Do not run as migration.
-- Generated by: scripts/fetch-storage-info.js
-- =====================================================

-- =====================================================
-- STORAGE BUCKETS CONFIGURATION
-- =====================================================
-- Total Buckets: 12


-- Bucket: employee-documents
-- ID: employee-documents
-- Public: true
-- Created: 2025-09-27T06:44:19.983Z
-- File Size Limit: 10485760
-- Allowed MIME Types: image/jpeg, image/jpg, image/png, image/webp, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document


-- Bucket: user-avatars
-- ID: user-avatars
-- Public: true
-- Created: 2025-09-27T09:37:55.546Z
-- File Size Limit: No limit
-- Allowed MIME Types: All types


-- Bucket: documents
-- ID: documents
-- Public: true
-- Created: 2025-09-29T21:07:24.977Z
-- File Size Limit: 10485760
-- Allowed MIME Types: application/pdf, image/jpeg, image/png, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain


-- Bucket: original-bills
-- ID: original-bills
-- Public: true
-- Created: 2025-10-16T09:39:29.747Z
-- File Size Limit: 52428800
-- Allowed MIME Types: application/pdf, image/jpeg, image/jpg, image/png, image/gif, image/bmp, image/webp


-- Bucket: vendor-contracts
-- ID: vendor-contracts
-- Public: true
-- Created: 2025-09-20T10:53:24.356Z
-- File Size Limit: 52428800
-- Allowed MIME Types: application/pdf


-- Bucket: pr-excel-files
-- ID: pr-excel-files
-- Public: true
-- Created: 2025-10-18T19:05:27.954Z
-- File Size Limit: 52428800
-- Allowed MIME Types: application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/excel, application/x-excel, application/x-msexcel


-- Bucket: requisition-images
-- ID: requisition-images
-- Public: true
-- Created: 2025-10-26T15:56:44.886Z
-- File Size Limit: 5242880
-- Allowed MIME Types: image/png, image/jpeg, image/jpg, application/pdf


-- Bucket: notification-images
-- ID: notification-images
-- Public: true
-- Created: 2025-10-05T08:21:22.199Z
-- File Size Limit: 52428800
-- Allowed MIME Types: image/jpeg, image/png, image/gif, image/webp, image/svg+xml, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, text/csv, text/plain, application/sql, text/sql


-- Bucket: task-images
-- ID: task-images
-- Public: true
-- Created: 2025-09-29T21:07:24.977Z
-- File Size Limit: 52428800
-- Allowed MIME Types: image/jpeg, image/png, image/gif, image/webp, image/svg+xml, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, text/csv, text/plain, application/sql, text/sql


-- Bucket: quick-task-files
-- ID: quick-task-files
-- Public: true
-- Created: 2025-10-06T11:32:05.112Z
-- File Size Limit: 52428800
-- Allowed MIME Types: image/jpeg, image/png, image/gif, image/webp, application/pdf, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain, text/csv


-- Bucket: completion-photos
-- ID: completion-photos
-- Public: true
-- Created: 2025-09-29T21:07:24.977Z
-- File Size Limit: 52428800
-- Allowed MIME Types: image/jpeg, image/png, image/webp, image/gif


-- Bucket: clearance-certificates
-- ID: clearance-certificates
-- Public: true
-- Created: 2025-10-16T07:51:17.889Z
-- File Size Limit: 10485760
-- Allowed MIME Types: image/png, image/jpeg, application/pdf


-- =====================================================
-- STORAGE OBJECTS SUMMARY
-- =====================================================
-- Object counts per bucket

-- Bucket: employee-documents - 0 objects
-- Bucket: user-avatars - 0 objects
-- Bucket: documents - 0 objects
-- Bucket: original-bills - 172 objects
-- Bucket: vendor-contracts - 0 objects
-- Bucket: pr-excel-files - 131 objects
-- Bucket: requisition-images - 6 objects
-- Bucket: notification-images - 1 objects
-- Bucket: task-images - 3 objects
-- Bucket: quick-task-files - 18 objects
-- Bucket: completion-photos - 6 objects
-- Bucket: clearance-certificates - 283 objects

-- =====================================================
-- DATABASE TABLES
-- =====================================================
-- Total Tables: 0



-- =====================================================
-- TABLE RELATIONSHIPS (FOREIGN KEYS)
-- =====================================================
-- Total Foreign Keys: 0



-- =====================================================
-- DATABASE STATISTICS
-- =====================================================

-- Total Tables: 0
-- Total Views: 0
-- Total Functions: 0
-- Storage Buckets: 0
-- Storage Objects: 0
-- Total Storage Size: 0 MB
-- Database Size: Unknown

-- =====================================================
-- END OF REFERENCE FILE
-- =====================================================
