-- Settlement rules for HR services (travel tickets and leave salary)

CREATE TABLE public.settlement_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_type text NOT NULL,
    rule_name text NOT NULL,
    qualification_cycle_years integer NOT NULL DEFAULT 1,
    ticket_count integer,
    entitled_days integer,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid,
    CONSTRAINT settlement_rules_rule_type_check CHECK (rule_type IN ('ticket', 'leave_salary')),
    CONSTRAINT settlement_rules_rule_name_check CHECK (btrim(rule_name) <> ''),
    CONSTRAINT settlement_rules_qualification_cycle_check CHECK (qualification_cycle_years > 0),
    CONSTRAINT settlement_rules_ticket_count_check CHECK (ticket_count IS NULL OR ticket_count > 0),
    CONSTRAINT settlement_rules_entitled_days_check CHECK (entitled_days IS NULL OR entitled_days > 0),
    CONSTRAINT settlement_rules_payload_check CHECK (
        (
            rule_type = 'ticket'
            AND ticket_count IS NOT NULL
            AND entitled_days IS NULL
        )
        OR
        (
            rule_type = 'leave_salary'
            AND entitled_days IS NOT NULL
            AND ticket_count IS NULL
        )
    )
);

CREATE INDEX settlement_rules_rule_type_idx
    ON public.settlement_rules USING btree (rule_type);

CREATE INDEX settlement_rules_is_active_idx
    ON public.settlement_rules USING btree (is_active);

CREATE OR REPLACE FUNCTION public.update_settlement_rules_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER set_settlement_rules_updated_at
BEFORE UPDATE ON public.settlement_rules
FOR EACH ROW
EXECUTE FUNCTION public.update_settlement_rules_updated_at();

ALTER TABLE public.settlement_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon all settlement_rules" ON public.settlement_rules
    TO anon
    USING (true)
    WITH CHECK (true);

CREATE POLICY authenticated_full_access ON public.settlement_rules
    USING (auth.uid() IS NOT NULL)
    WITH CHECK (auth.uid() IS NOT NULL);

GRANT ALL ON TABLE public.settlement_rules TO anon;
GRANT ALL ON TABLE public.settlement_rules TO authenticated;
GRANT ALL ON TABLE public.settlement_rules TO service_role;
GRANT SELECT ON TABLE public.settlement_rules TO replication_user;
