-- Add multi-period applicability rule schedules with effective from/to and infinite support

CREATE TABLE IF NOT EXISTS public.hr_employee_applicability_rule_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id text NOT NULL,
    rule_type text NOT NULL,
    rule_id bigint NOT NULL,
    sequence_no integer NOT NULL,
    duration_years integer NOT NULL DEFAULT 0,
    duration_months integer NOT NULL DEFAULT 0,
    effective_from date NOT NULL,
    effective_to date,
    is_infinite boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT hr_employee_applicability_rule_periods_employee_fkey
        FOREIGN KEY (employee_id) REFERENCES public.hr_employee_master(id) ON DELETE CASCADE,
    CONSTRAINT hr_employee_applicability_rule_periods_rule_fkey
        FOREIGN KEY (rule_id) REFERENCES public.settlement_rules(id) ON DELETE CASCADE,
    CONSTRAINT hr_employee_applicability_rule_periods_type_check
        CHECK (rule_type IN ('ticket', 'leave_salary')),
    CONSTRAINT hr_employee_applicability_rule_periods_duration_check
        CHECK (
            (is_infinite = true AND effective_to IS NULL)
            OR (is_infinite = false AND effective_to IS NOT NULL AND effective_to >= effective_from)
        ),
    CONSTRAINT hr_employee_applicability_rule_periods_unique_seq
        UNIQUE (employee_id, rule_type, sequence_no)
);

CREATE INDEX IF NOT EXISTS hr_employee_applicability_rule_periods_employee_type_idx
    ON public.hr_employee_applicability_rule_periods (employee_id, rule_type);

CREATE INDEX IF NOT EXISTS hr_employee_applicability_rule_periods_effective_idx
    ON public.hr_employee_applicability_rule_periods (employee_id, rule_type, effective_from, effective_to);

CREATE OR REPLACE FUNCTION public.update_hr_employee_applicability_rule_periods_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_hr_employee_applicability_rule_periods_updated_at
    ON public.hr_employee_applicability_rule_periods;

CREATE TRIGGER set_hr_employee_applicability_rule_periods_updated_at
BEFORE UPDATE ON public.hr_employee_applicability_rule_periods
FOR EACH ROW
EXECUTE FUNCTION public.update_hr_employee_applicability_rule_periods_updated_at();

ALTER TABLE public.hr_employee_applicability_rule_periods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon all hr_employee_applicability_rule_periods"
    ON public.hr_employee_applicability_rule_periods;
CREATE POLICY "Allow anon all hr_employee_applicability_rule_periods"
    ON public.hr_employee_applicability_rule_periods
    TO anon
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS authenticated_full_access_hr_employee_applicability_rule_periods
    ON public.hr_employee_applicability_rule_periods;
CREATE POLICY authenticated_full_access_hr_employee_applicability_rule_periods
    ON public.hr_employee_applicability_rule_periods
    USING (auth.uid() IS NOT NULL)
    WITH CHECK (auth.uid() IS NOT NULL);

GRANT ALL ON TABLE public.hr_employee_applicability_rule_periods TO anon;
GRANT ALL ON TABLE public.hr_employee_applicability_rule_periods TO authenticated;
GRANT ALL ON TABLE public.hr_employee_applicability_rule_periods TO service_role;
GRANT SELECT ON TABLE public.hr_employee_applicability_rule_periods TO replication_user;

CREATE OR REPLACE FUNCTION public.get_hr_employee_rule_periods(
    p_employee_id text,
    p_rule_type text
)
RETURNS TABLE (
    id bigint,
    sequence_no integer,
    rule_id bigint,
    rule_name_en text,
    rule_name_ar text,
    duration_years integer,
    duration_months integer,
    effective_from date,
    effective_to date,
    is_infinite boolean
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        p.id,
        p.sequence_no,
        p.rule_id,
        r.rule_name_en::text,
        r.rule_name_ar::text,
        p.duration_years,
        p.duration_months,
        p.effective_from,
        p.effective_to,
        p.is_infinite
    FROM public.hr_employee_applicability_rule_periods p
    JOIN public.settlement_rules r
        ON r.id = p.rule_id
    WHERE p.employee_id = p_employee_id
        AND p.rule_type = p_rule_type
    ORDER BY p.sequence_no ASC;
$$;

CREATE OR REPLACE FUNCTION public.save_hr_employee_rule_periods(
    p_employee_id text,
    p_rule_type text,
    p_periods jsonb DEFAULT '[]'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_join_date date;
    v_item jsonb;
    v_seq integer := 0;
    v_start_date date;
    v_end_date date;
    v_rule_id bigint;
    v_is_infinite boolean;
    v_duration_years integer;
    v_duration_months integer;
    v_rule public.settlement_rules%ROWTYPE;
    v_active_rule_id bigint;
    v_active_rule public.settlement_rules%ROWTYPE;
    v_total_months integer;
    v_cycle_months integer;
    v_completed_cycles integer;
    v_qualified integer;
BEGIN
    IF p_employee_id IS NULL OR BTRIM(p_employee_id) = '' THEN
        RAISE EXCEPTION 'p_employee_id is required';
    END IF;

    IF p_rule_type NOT IN ('ticket', 'leave_salary') THEN
        RAISE EXCEPTION 'p_rule_type must be ticket or leave_salary';
    END IF;

    SELECT e.join_date INTO v_join_date
    FROM public.hr_employee_master e
    WHERE e.id = p_employee_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Employee % was not found', p_employee_id;
    END IF;

    DELETE FROM public.hr_employee_applicability_rule_periods
    WHERE employee_id = p_employee_id
      AND rule_type = p_rule_type;

    IF p_periods IS NULL OR jsonb_typeof(p_periods) <> 'array' OR jsonb_array_length(p_periods) = 0 THEN
        INSERT INTO public.hr_employee_settlement_applicability (employee_id)
        VALUES (p_employee_id)
        ON CONFLICT (employee_id) DO NOTHING;

        IF p_rule_type = 'ticket' THEN
            UPDATE public.hr_employee_settlement_applicability
            SET
                ticket_rule_id = NULL,
                ticket_rule_enabled = false,
                qualified_ticket_count = NULL
            WHERE employee_id = p_employee_id;
        ELSE
            UPDATE public.hr_employee_settlement_applicability
            SET
                leave_salary_rule_id = NULL,
                leave_salary_rule_enabled = false,
                qualified_leave_days = NULL
            WHERE employee_id = p_employee_id;
        END IF;

        RETURN;
    END IF;

    v_start_date := COALESCE(v_join_date, CURRENT_DATE);

    FOR v_item IN SELECT * FROM jsonb_array_elements(p_periods)
    LOOP
        v_seq := v_seq + 1;
        v_rule_id := NULLIF(v_item ->> 'rule_id', '')::bigint;
        v_is_infinite := COALESCE((v_item ->> 'is_infinite')::boolean, false);
        v_duration_years := GREATEST(0, COALESCE((v_item ->> 'duration_years')::integer, 0));
        v_duration_months := GREATEST(0, COALESCE((v_item ->> 'duration_months')::integer, 0));

        IF v_rule_id IS NULL THEN
            RAISE EXCEPTION 'rule_id is required for each period';
        END IF;

        IF v_is_infinite = false AND v_duration_years = 0 AND v_duration_months = 0 THEN
            RAISE EXCEPTION 'Duration is required for non-infinite periods';
        END IF;

        SELECT * INTO v_rule
        FROM public.settlement_rules r
        WHERE r.id = v_rule_id
            AND r.rule_type = p_rule_type
            AND r.is_active = true;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Active settlement rule % of type % was not found', v_rule_id, p_rule_type;
        END IF;

        IF v_is_infinite THEN
            v_end_date := NULL;
        ELSE
            v_end_date := (
                v_start_date
                + make_interval(years => v_duration_years, months => v_duration_months)
                - interval '1 day'
            )::date;
        END IF;

        INSERT INTO public.hr_employee_applicability_rule_periods (
            employee_id,
            rule_type,
            rule_id,
            sequence_no,
            duration_years,
            duration_months,
            effective_from,
            effective_to,
            is_infinite
        )
        VALUES (
            p_employee_id,
            p_rule_type,
            v_rule_id,
            v_seq,
            v_duration_years,
            v_duration_months,
            v_start_date,
            v_end_date,
            v_is_infinite
        );

        EXIT WHEN v_is_infinite;
        v_start_date := v_end_date + 1;
    END LOOP;

    SELECT p.rule_id
    INTO v_active_rule_id
    FROM public.hr_employee_applicability_rule_periods p
    WHERE p.employee_id = p_employee_id
        AND p.rule_type = p_rule_type
        AND p.effective_from <= CURRENT_DATE
        AND (p.is_infinite = true OR p.effective_to >= CURRENT_DATE)
    ORDER BY p.effective_from DESC
    LIMIT 1;

    IF v_active_rule_id IS NULL THEN
        INSERT INTO public.hr_employee_settlement_applicability (employee_id)
        VALUES (p_employee_id)
        ON CONFLICT (employee_id) DO NOTHING;

        IF p_rule_type = 'ticket' THEN
            UPDATE public.hr_employee_settlement_applicability
            SET
                ticket_rule_id = NULL,
                ticket_rule_enabled = false,
                qualified_ticket_count = NULL
            WHERE employee_id = p_employee_id;
        ELSE
            UPDATE public.hr_employee_settlement_applicability
            SET
                leave_salary_rule_id = NULL,
                leave_salary_rule_enabled = false,
                qualified_leave_days = NULL
            WHERE employee_id = p_employee_id;
        END IF;

        RETURN;
    END IF;

    SELECT * INTO v_active_rule
    FROM public.settlement_rules r
    WHERE r.id = v_active_rule_id;

    IF v_join_date IS NULL OR v_join_date > CURRENT_DATE THEN
        v_completed_cycles := 0;
    ELSE
        v_total_months :=
            (EXTRACT(YEAR FROM age(CURRENT_DATE, v_join_date))::int * 12)
            + EXTRACT(MONTH FROM age(CURRENT_DATE, v_join_date))::int;

        v_cycle_months := GREATEST(
            1,
            COALESCE(v_active_rule.qualification_cycle_value, v_active_rule.qualification_cycle_years, 1)
            * CASE WHEN COALESCE(v_active_rule.qualification_cycle_unit, 'year') = 'month' THEN 1 ELSE 12 END
        );

        v_completed_cycles := GREATEST(0, FLOOR(v_total_months::numeric / v_cycle_months)::int);
    END IF;

    INSERT INTO public.hr_employee_settlement_applicability (employee_id)
    VALUES (p_employee_id)
    ON CONFLICT (employee_id) DO NOTHING;

    IF p_rule_type = 'ticket' THEN
        v_qualified := v_completed_cycles * COALESCE(v_active_rule.ticket_count, 0);
        UPDATE public.hr_employee_settlement_applicability
        SET
            ticket_rule_id = v_active_rule.id,
            ticket_rule_enabled = true,
            qualified_ticket_count = v_qualified
        WHERE employee_id = p_employee_id;
    ELSE
        v_qualified := v_completed_cycles * COALESCE(v_active_rule.entitled_days, 0);
        UPDATE public.hr_employee_settlement_applicability
        SET
            leave_salary_rule_id = v_active_rule.id,
            leave_salary_rule_enabled = true,
            qualified_leave_days = v_qualified
        WHERE employee_id = p_employee_id;
    END IF;
END;
$$;

DROP FUNCTION IF EXISTS public.get_hr_employee_applicability(integer, integer, text, text, boolean, boolean);

CREATE OR REPLACE FUNCTION public.get_hr_employee_applicability(
    p_limit integer DEFAULT 50,
    p_offset integer DEFAULT 0,
    p_name_search text DEFAULT NULL,
    p_nationality_id text DEFAULT NULL,
    p_ticket_enabled boolean DEFAULT NULL,
    p_leave_enabled boolean DEFAULT NULL
)
RETURNS TABLE (
    applicability_id bigint,
    employee_id text,
    employee_name_en text,
    employee_name_ar text,
    nationality_id text,
    nationality_name_en text,
    nationality_name_ar text,
    sponsorship_status boolean,
    join_date date,
    employment_status text,
    ticket_rule_id bigint,
    ticket_rule_enabled boolean,
    ticket_rule_name_en text,
    ticket_rule_name_ar text,
    qualified_ticket_count integer,
    ticket_periods_count integer,
    leave_salary_rule_id bigint,
    leave_salary_rule_enabled boolean,
    leave_rule_name_en text,
    leave_rule_name_ar text,
    qualified_leave_days integer,
    leave_periods_count integer,
    total_count bigint
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    WITH base AS (
        SELECT
            a.id AS applicability_id,
            e.id::text AS employee_id,
            e.name_en::text AS employee_name_en,
            e.name_ar::text AS employee_name_ar,
            e.nationality_id::text AS nationality_id,
            n.name_en::text AS nationality_name_en,
            n.name_ar::text AS nationality_name_ar,
            e.sponsorship_status,
            e.join_date,
            e.employment_status::text AS employment_status,
            COALESCE(tp.rule_id, a.ticket_rule_id) AS ticket_rule_id,
            CASE WHEN tp.rule_id IS NOT NULL THEN true ELSE COALESCE(a.ticket_rule_enabled, false) END AS ticket_rule_enabled,
            COALESCE(tp.rule_name_en, tr.rule_name_en)::text AS ticket_rule_name_en,
            COALESCE(tp.rule_name_ar, tr.rule_name_ar)::text AS ticket_rule_name_ar,
            a.qualified_ticket_count,
            (
                SELECT COUNT(*)::integer
                FROM public.hr_employee_applicability_rule_periods p
                WHERE p.employee_id = e.id
                    AND p.rule_type = 'ticket'
            ) AS ticket_periods_count,
            COALESCE(lp.rule_id, a.leave_salary_rule_id) AS leave_salary_rule_id,
            CASE WHEN lp.rule_id IS NOT NULL THEN true ELSE COALESCE(a.leave_salary_rule_enabled, false) END AS leave_salary_rule_enabled,
            COALESCE(lp.rule_name_en, lr.rule_name_en)::text AS leave_rule_name_en,
            COALESCE(lp.rule_name_ar, lr.rule_name_ar)::text AS leave_rule_name_ar,
            a.qualified_leave_days,
            (
                SELECT COUNT(*)::integer
                FROM public.hr_employee_applicability_rule_periods p
                WHERE p.employee_id = e.id
                    AND p.rule_type = 'leave_salary'
            ) AS leave_periods_count
        FROM public.hr_employee_master e
        LEFT JOIN public.hr_employee_settlement_applicability a
            ON a.employee_id = e.id
        LEFT JOIN public.nationalities n
            ON n.id = e.nationality_id
        LEFT JOIN public.settlement_rules tr
            ON tr.id = a.ticket_rule_id
        LEFT JOIN public.settlement_rules lr
            ON lr.id = a.leave_salary_rule_id
        LEFT JOIN LATERAL (
            SELECT
                p.rule_id,
                r.rule_name_en,
                r.rule_name_ar
            FROM public.hr_employee_applicability_rule_periods p
            JOIN public.settlement_rules r ON r.id = p.rule_id
            WHERE p.employee_id = e.id
                AND p.rule_type = 'ticket'
                AND p.effective_from <= CURRENT_DATE
                AND (p.is_infinite = true OR p.effective_to >= CURRENT_DATE)
            ORDER BY p.effective_from DESC
            LIMIT 1
        ) tp ON true
        LEFT JOIN LATERAL (
            SELECT
                p.rule_id,
                r.rule_name_en,
                r.rule_name_ar
            FROM public.hr_employee_applicability_rule_periods p
            JOIN public.settlement_rules r ON r.id = p.rule_id
            WHERE p.employee_id = e.id
                AND p.rule_type = 'leave_salary'
                AND p.effective_from <= CURRENT_DATE
                AND (p.is_infinite = true OR p.effective_to >= CURRENT_DATE)
            ORDER BY p.effective_from DESC
            LIMIT 1
        ) lp ON true
        WHERE e.employment_status = ANY (ARRAY['Job (With Finger)', 'Remote Job', 'Vacation'])
    ),
    filtered AS (
        SELECT *
        FROM base b
        WHERE (
                p_name_search IS NULL OR BTRIM(p_name_search) = ''
                OR COALESCE(b.employee_name_en, '') ILIKE '%' || BTRIM(p_name_search) || '%'
                OR COALESCE(b.employee_name_ar, '') ILIKE '%' || BTRIM(p_name_search) || '%'
                OR b.employee_id ILIKE '%' || BTRIM(p_name_search) || '%'
            )
            AND (
                p_nationality_id IS NULL OR BTRIM(p_nationality_id) = ''
                OR b.nationality_id = BTRIM(p_nationality_id)
            )
            AND (
                p_ticket_enabled IS NULL
                OR b.ticket_rule_enabled = p_ticket_enabled
            )
            AND (
                p_leave_enabled IS NULL
                OR b.leave_salary_rule_enabled = p_leave_enabled
            )
    )
    SELECT
        f.applicability_id,
        f.employee_id,
        f.employee_name_en,
        f.employee_name_ar,
        f.nationality_id,
        f.nationality_name_en,
        f.nationality_name_ar,
        f.sponsorship_status,
        f.join_date,
        f.employment_status,
        f.ticket_rule_id,
        f.ticket_rule_enabled,
        f.ticket_rule_name_en,
        f.ticket_rule_name_ar,
        f.qualified_ticket_count,
        f.ticket_periods_count,
        f.leave_salary_rule_id,
        f.leave_salary_rule_enabled,
        f.leave_rule_name_en,
        f.leave_rule_name_ar,
        f.qualified_leave_days,
        f.leave_periods_count,
        COUNT(*) OVER() AS total_count
    FROM filtered f
    ORDER BY
        CASE
            WHEN LOWER(COALESCE(f.nationality_name_en, '')) = 'saudi arabia'
                OR COALESCE(f.nationality_name_ar, '') LIKE '%السعود%'
            THEN 0
            ELSE 1
        END,
        LOWER(COALESCE(f.employee_name_en, '')),
        f.employee_id
    LIMIT GREATEST(COALESCE(p_limit, 50), 1)
    OFFSET GREATEST(COALESCE(p_offset, 0), 0);
$$;

GRANT EXECUTE ON FUNCTION public.get_hr_employee_rule_periods(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_hr_employee_rule_periods(text, text) TO anon;

GRANT EXECUTE ON FUNCTION public.save_hr_employee_rule_periods(text, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_hr_employee_rule_periods(text, text, jsonb) TO anon;

GRANT EXECUTE ON FUNCTION public.get_hr_employee_applicability(integer, integer, text, text, boolean, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_hr_employee_applicability(integer, integer, text, text, boolean, boolean) TO anon;
