-- Employee applicability mapping for settlement and annual leave rules

CREATE TABLE public.hr_employee_settlement_applicability (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id text NOT NULL,
    ticket_rule_id bigint,
    ticket_rule_enabled boolean NOT NULL DEFAULT false,
    qualified_ticket_count integer,
    leave_salary_rule_id bigint,
    leave_salary_rule_enabled boolean NOT NULL DEFAULT false,
    qualified_leave_days integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT hr_employee_settlement_applicability_employee_id_key UNIQUE (employee_id),
    CONSTRAINT hr_employee_settlement_applicability_employee_id_fkey
        FOREIGN KEY (employee_id) REFERENCES public.hr_employee_master(id) ON DELETE CASCADE,
    CONSTRAINT hr_employee_settlement_applicability_ticket_rule_id_fkey
        FOREIGN KEY (ticket_rule_id) REFERENCES public.settlement_rules(id) ON DELETE SET NULL,
    CONSTRAINT hr_employee_settlement_applicability_leave_salary_rule_id_fkey
        FOREIGN KEY (leave_salary_rule_id) REFERENCES public.settlement_rules(id) ON DELETE SET NULL,
    CONSTRAINT hr_employee_settlement_applicability_ticket_nonnegative_check
        CHECK (qualified_ticket_count IS NULL OR qualified_ticket_count >= 0),
    CONSTRAINT hr_employee_settlement_applicability_leave_nonnegative_check
        CHECK (qualified_leave_days IS NULL OR qualified_leave_days >= 0)
);

CREATE INDEX hr_employee_settlement_applicability_ticket_rule_idx
    ON public.hr_employee_settlement_applicability USING btree (ticket_rule_id);

CREATE INDEX hr_employee_settlement_applicability_leave_rule_idx
    ON public.hr_employee_settlement_applicability USING btree (leave_salary_rule_id);

CREATE OR REPLACE FUNCTION public.update_hr_employee_settlement_applicability_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER set_hr_employee_settlement_applicability_updated_at
BEFORE UPDATE ON public.hr_employee_settlement_applicability
FOR EACH ROW
EXECUTE FUNCTION public.update_hr_employee_settlement_applicability_updated_at();

ALTER TABLE public.hr_employee_settlement_applicability ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon all hr_employee_settlement_applicability"
    ON public.hr_employee_settlement_applicability
    TO anon
    USING (true)
    WITH CHECK (true);

CREATE POLICY authenticated_full_access_hr_employee_settlement_applicability
    ON public.hr_employee_settlement_applicability
    USING (auth.uid() IS NOT NULL)
    WITH CHECK (auth.uid() IS NOT NULL);

GRANT ALL ON TABLE public.hr_employee_settlement_applicability TO anon;
GRANT ALL ON TABLE public.hr_employee_settlement_applicability TO authenticated;
GRANT ALL ON TABLE public.hr_employee_settlement_applicability TO service_role;
GRANT SELECT ON TABLE public.hr_employee_settlement_applicability TO replication_user;
