-- ESOB system: manager-editable rules + employee ESOB records

CREATE TABLE IF NOT EXISTS public.hr_esob_base_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name_en text NOT NULL,
    rule_name_ar text,
    years_from numeric(8,2) NOT NULL DEFAULT 0,
    years_to numeric(8,2),
    months_per_year numeric(8,4) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT hr_esob_base_rules_years_chk CHECK (years_from >= 0 AND (years_to IS NULL OR years_to >= years_from)),
    CONSTRAINT hr_esob_base_rules_months_chk CHECK (months_per_year > 0)
);

CREATE TABLE IF NOT EXISTS public.hr_esob_resignation_factors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name_en text NOT NULL,
    rule_name_ar text,
    years_from numeric(8,2) NOT NULL DEFAULT 0,
    years_to numeric(8,2),
    factor numeric(8,4) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT hr_esob_resignation_factors_years_chk CHECK (years_from >= 0 AND (years_to IS NULL OR years_to >= years_from)),
    CONSTRAINT hr_esob_resignation_factors_factor_chk CHECK (factor >= 0 AND factor <= 1)
);

CREATE TABLE IF NOT EXISTS public.hr_employee_esob_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id text NOT NULL,
    service_start_date date NOT NULL,
    service_end_date date NOT NULL,
    termination_mode text NOT NULL,
    include_basic_salary boolean NOT NULL DEFAULT true,
    include_other_allowance boolean NOT NULL DEFAULT false,
    include_accommodation_allowance boolean NOT NULL DEFAULT false,
    include_travel_allowance boolean NOT NULL DEFAULT false,
    include_food_allowance boolean NOT NULL DEFAULT false,
    unused_leave_days numeric(10,2) NOT NULL DEFAULT 0,
    unused_ticket_count integer NOT NULL DEFAULT 0,
    ticket_amount numeric(12,2) NOT NULL DEFAULT 0,
    manual_additions numeric(12,2) NOT NULL DEFAULT 0,
    manual_deductions numeric(12,2) NOT NULL DEFAULT 0,
    notes text,
    print_language text NOT NULL DEFAULT 'bilingual',
    calc_service_years numeric(10,2) NOT NULL DEFAULT 0,
    calc_monthly_wage numeric(12,2) NOT NULL DEFAULT 0,
    calc_esob_amount numeric(12,2) NOT NULL DEFAULT 0,
    calc_leave_amount numeric(12,2) NOT NULL DEFAULT 0,
    calc_ticket_amount numeric(12,2) NOT NULL DEFAULT 0,
    calc_gross_amount numeric(12,2) NOT NULL DEFAULT 0,
    calc_net_amount numeric(12,2) NOT NULL DEFAULT 0,
    created_by uuid,
    updated_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT hr_employee_esob_records_mode_chk CHECK (termination_mode IN ('resignation', 'non_resignation')),
    CONSTRAINT hr_employee_esob_records_print_lang_chk CHECK (print_language IN ('en', 'ar', 'bilingual')),
    CONSTRAINT hr_employee_esob_records_dates_chk CHECK (service_end_date >= service_start_date),
    CONSTRAINT hr_employee_esob_records_leave_chk CHECK (unused_leave_days >= 0),
    CONSTRAINT hr_employee_esob_records_ticket_cnt_chk CHECK (unused_ticket_count >= 0),
    CONSTRAINT hr_employee_esob_records_amounts_chk CHECK (
        ticket_amount >= 0
        AND manual_additions >= 0
        AND manual_deductions >= 0
        AND calc_service_years >= 0
        AND calc_monthly_wage >= 0
        AND calc_esob_amount >= 0
        AND calc_leave_amount >= 0
        AND calc_ticket_amount >= 0
    )
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'hr_employee_esob_records_employee_id_fkey'
    ) THEN
        ALTER TABLE public.hr_employee_esob_records
            ADD CONSTRAINT hr_employee_esob_records_employee_id_fkey
            FOREIGN KEY (employee_id) REFERENCES public.hr_employee_master(id) ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_hr_esob_base_rules_years ON public.hr_esob_base_rules (years_from, years_to);
CREATE INDEX IF NOT EXISTS idx_hr_esob_resignation_factors_years ON public.hr_esob_resignation_factors (years_from, years_to);
CREATE INDEX IF NOT EXISTS idx_hr_employee_esob_records_employee_id ON public.hr_employee_esob_records (employee_id);
CREATE INDEX IF NOT EXISTS idx_hr_employee_esob_records_updated_at ON public.hr_employee_esob_records (updated_at DESC);

CREATE OR REPLACE FUNCTION public.touch_hr_esob_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_hr_esob_base_rules ON public.hr_esob_base_rules;
CREATE TRIGGER trg_touch_hr_esob_base_rules
BEFORE UPDATE ON public.hr_esob_base_rules
FOR EACH ROW
EXECUTE FUNCTION public.touch_hr_esob_updated_at();

DROP TRIGGER IF EXISTS trg_touch_hr_esob_resignation_factors ON public.hr_esob_resignation_factors;
CREATE TRIGGER trg_touch_hr_esob_resignation_factors
BEFORE UPDATE ON public.hr_esob_resignation_factors
FOR EACH ROW
EXECUTE FUNCTION public.touch_hr_esob_updated_at();

DROP TRIGGER IF EXISTS trg_touch_hr_employee_esob_records ON public.hr_employee_esob_records;
CREATE TRIGGER trg_touch_hr_employee_esob_records
BEFORE UPDATE ON public.hr_employee_esob_records
FOR EACH ROW
EXECUTE FUNCTION public.touch_hr_esob_updated_at();

INSERT INTO public.hr_esob_base_rules (rule_name_en, rule_name_ar, years_from, years_to, months_per_year, sort_order)
SELECT 'Base Rule: First 5 Years', 'قاعدة أساسية: أول 5 سنوات', 0, 5, 0.5, 0
WHERE NOT EXISTS (
    SELECT 1 FROM public.hr_esob_base_rules
    WHERE years_from = 0 AND years_to = 5 AND months_per_year = 0.5
);

INSERT INTO public.hr_esob_base_rules (rule_name_en, rule_name_ar, years_from, years_to, months_per_year, sort_order)
SELECT 'Base Rule: Over 5 Years', 'قاعدة أساسية: أكثر من 5 سنوات', 5, NULL, 1, 5
WHERE NOT EXISTS (
    SELECT 1 FROM public.hr_esob_base_rules
    WHERE years_from = 5 AND years_to IS NULL AND months_per_year = 1
);

INSERT INTO public.hr_esob_resignation_factors (rule_name_en, rule_name_ar, years_from, years_to, factor, sort_order)
SELECT 'Resignation Factor: Less than 2 Years', 'معامل الاستقالة: أقل من سنتين', 0, 2, 0, 0
WHERE NOT EXISTS (
    SELECT 1 FROM public.hr_esob_resignation_factors
    WHERE years_from = 0 AND years_to = 2 AND factor = 0
);

INSERT INTO public.hr_esob_resignation_factors (rule_name_en, rule_name_ar, years_from, years_to, factor, sort_order)
SELECT 'Resignation Factor: 2 to 5 Years', 'معامل الاستقالة: من 2 إلى 5 سنوات', 2, 5, 0.3333, 2
WHERE NOT EXISTS (
    SELECT 1 FROM public.hr_esob_resignation_factors
    WHERE years_from = 2 AND years_to = 5 AND factor = 0.3333
);

INSERT INTO public.hr_esob_resignation_factors (rule_name_en, rule_name_ar, years_from, years_to, factor, sort_order)
SELECT 'Resignation Factor: 5 to 10 Years', 'معامل الاستقالة: من 5 إلى 10 سنوات', 5, 10, 0.6667, 5
WHERE NOT EXISTS (
    SELECT 1 FROM public.hr_esob_resignation_factors
    WHERE years_from = 5 AND years_to = 10 AND factor = 0.6667
);

INSERT INTO public.hr_esob_resignation_factors (rule_name_en, rule_name_ar, years_from, years_to, factor, sort_order)
SELECT 'Resignation Factor: 10+ Years', 'معامل الاستقالة: 10 سنوات فأكثر', 10, NULL, 1, 10
WHERE NOT EXISTS (
    SELECT 1 FROM public.hr_esob_resignation_factors
    WHERE years_from = 10 AND years_to IS NULL AND factor = 1
);

ALTER TABLE public.hr_esob_base_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_esob_resignation_factors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_employee_esob_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to hr_esob_base_rules" ON public.hr_esob_base_rules;
CREATE POLICY "Allow all access to hr_esob_base_rules"
ON public.hr_esob_base_rules
FOR ALL
TO anon
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all access to hr_esob_resignation_factors" ON public.hr_esob_resignation_factors;
CREATE POLICY "Allow all access to hr_esob_resignation_factors"
ON public.hr_esob_resignation_factors
FOR ALL
TO anon
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all access to hr_employee_esob_records" ON public.hr_employee_esob_records;
CREATE POLICY "Allow all access to hr_employee_esob_records"
ON public.hr_employee_esob_records
FOR ALL
TO anon
USING (true)
WITH CHECK (true);

GRANT ALL ON TABLE public.hr_esob_base_rules TO anon;
GRANT ALL ON TABLE public.hr_esob_base_rules TO authenticated;
GRANT ALL ON TABLE public.hr_esob_base_rules TO service_role;

GRANT ALL ON TABLE public.hr_esob_resignation_factors TO anon;
GRANT ALL ON TABLE public.hr_esob_resignation_factors TO authenticated;
GRANT ALL ON TABLE public.hr_esob_resignation_factors TO service_role;

GRANT ALL ON TABLE public.hr_employee_esob_records TO anon;
GRANT ALL ON TABLE public.hr_employee_esob_records TO authenticated;
GRANT ALL ON TABLE public.hr_employee_esob_records TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
