-- Track consumed qualified tickets and leave days, and expose current-period usage via RPC

CREATE TABLE IF NOT EXISTS public.hr_employee_ticket_issuances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id text NOT NULL,
    issuance_date date NOT NULL,
    ticket_count integer NOT NULL CHECK (ticket_count > 0),
    ticket_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (ticket_amount >= 0),
    is_paid boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT hr_employee_ticket_issuances_employee_fkey
        FOREIGN KEY (employee_id) REFERENCES public.hr_employee_master(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS hr_employee_ticket_issuances_employee_date_idx
    ON public.hr_employee_ticket_issuances (employee_id, issuance_date);

CREATE TABLE IF NOT EXISTS public.hr_employee_leave_approvals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id text NOT NULL,
    leave_date date NOT NULL,
    is_paid boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT hr_employee_leave_approvals_employee_fkey
        FOREIGN KEY (employee_id) REFERENCES public.hr_employee_master(id) ON DELETE CASCADE,
    CONSTRAINT hr_employee_leave_approvals_employee_date_key UNIQUE (employee_id, leave_date)
);

CREATE INDEX IF NOT EXISTS hr_employee_leave_approvals_employee_date_idx
    ON public.hr_employee_leave_approvals (employee_id, leave_date);

CREATE OR REPLACE FUNCTION public.update_hr_employee_ticket_issuances_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_hr_employee_ticket_issuances_updated_at
    ON public.hr_employee_ticket_issuances;
CREATE TRIGGER set_hr_employee_ticket_issuances_updated_at
BEFORE UPDATE ON public.hr_employee_ticket_issuances
FOR EACH ROW
EXECUTE FUNCTION public.update_hr_employee_ticket_issuances_updated_at();

CREATE OR REPLACE FUNCTION public.update_hr_employee_leave_approvals_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_hr_employee_leave_approvals_updated_at
    ON public.hr_employee_leave_approvals;
CREATE TRIGGER set_hr_employee_leave_approvals_updated_at
BEFORE UPDATE ON public.hr_employee_leave_approvals
FOR EACH ROW
EXECUTE FUNCTION public.update_hr_employee_leave_approvals_updated_at();

ALTER TABLE public.hr_employee_ticket_issuances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_employee_leave_approvals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon all hr_employee_ticket_issuances"
    ON public.hr_employee_ticket_issuances;
CREATE POLICY "Allow anon all hr_employee_ticket_issuances"
    ON public.hr_employee_ticket_issuances
    TO anon
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS authenticated_full_access_hr_employee_ticket_issuances
    ON public.hr_employee_ticket_issuances;
CREATE POLICY authenticated_full_access_hr_employee_ticket_issuances
    ON public.hr_employee_ticket_issuances
    USING (auth.uid() IS NOT NULL)
    WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Allow anon all hr_employee_leave_approvals"
    ON public.hr_employee_leave_approvals;
CREATE POLICY "Allow anon all hr_employee_leave_approvals"
    ON public.hr_employee_leave_approvals
    TO anon
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS authenticated_full_access_hr_employee_leave_approvals
    ON public.hr_employee_leave_approvals;
CREATE POLICY authenticated_full_access_hr_employee_leave_approvals
    ON public.hr_employee_leave_approvals
    USING (auth.uid() IS NOT NULL)
    WITH CHECK (auth.uid() IS NOT NULL);

GRANT ALL ON TABLE public.hr_employee_ticket_issuances TO anon;
GRANT ALL ON TABLE public.hr_employee_ticket_issuances TO authenticated;
GRANT ALL ON TABLE public.hr_employee_ticket_issuances TO service_role;
GRANT SELECT ON TABLE public.hr_employee_ticket_issuances TO replication_user;

GRANT ALL ON TABLE public.hr_employee_leave_approvals TO anon;
GRANT ALL ON TABLE public.hr_employee_leave_approvals TO authenticated;
GRANT ALL ON TABLE public.hr_employee_leave_approvals TO service_role;
GRANT SELECT ON TABLE public.hr_employee_leave_approvals TO replication_user;

CREATE OR REPLACE FUNCTION public.get_hr_employee_qualification_usage(
    p_employee_ids text[]
)
RETURNS TABLE (
    employee_id text,
    ticket_issued_count integer,
    leave_approved_days integer
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    WITH employees AS (
        SELECT DISTINCT e_id::text AS employee_id
        FROM unnest(COALESCE(p_employee_ids, ARRAY[]::text[])) AS e_id
        WHERE e_id IS NOT NULL AND btrim(e_id) <> ''
    ),
    active_ticket_period AS (
        SELECT DISTINCT ON (p.employee_id)
            p.employee_id,
            p.effective_from,
            p.effective_to,
            p.is_infinite
        FROM public.hr_employee_applicability_rule_periods p
        JOIN employees e ON e.employee_id = p.employee_id
        WHERE p.rule_type = 'ticket'
            AND p.effective_from <= CURRENT_DATE
            AND (p.is_infinite = true OR p.effective_to >= CURRENT_DATE)
        ORDER BY p.employee_id, p.effective_from DESC
    ),
    active_leave_period AS (
        SELECT DISTINCT ON (p.employee_id)
            p.employee_id,
            p.effective_from,
            p.effective_to,
            p.is_infinite
        FROM public.hr_employee_applicability_rule_periods p
        JOIN employees e ON e.employee_id = p.employee_id
        WHERE p.rule_type = 'leave_salary'
            AND p.effective_from <= CURRENT_DATE
            AND (p.is_infinite = true OR p.effective_to >= CURRENT_DATE)
        ORDER BY p.employee_id, p.effective_from DESC
    ),
    ticket_usage AS (
        SELECT
            e.employee_id,
            COALESCE(SUM(t.ticket_count), 0)::integer AS ticket_issued_count
        FROM employees e
        LEFT JOIN active_ticket_period ap ON ap.employee_id = e.employee_id
        LEFT JOIN public.hr_employee_ticket_issuances t
            ON t.employee_id = e.employee_id
            AND ap.employee_id IS NOT NULL
            AND t.issuance_date >= ap.effective_from
            AND (ap.is_infinite = true OR t.issuance_date <= ap.effective_to)
        GROUP BY e.employee_id
    ),
    leave_usage AS (
        SELECT
            e.employee_id,
            COALESCE(COUNT(l.id), 0)::integer AS leave_approved_days
        FROM employees e
        LEFT JOIN active_leave_period ap ON ap.employee_id = e.employee_id
        LEFT JOIN public.hr_employee_leave_approvals l
            ON l.employee_id = e.employee_id
            AND ap.employee_id IS NOT NULL
            AND l.leave_date >= ap.effective_from
            AND (ap.is_infinite = true OR l.leave_date <= ap.effective_to)
        GROUP BY e.employee_id
    )
    SELECT
        e.employee_id,
        COALESCE(t.ticket_issued_count, 0) AS ticket_issued_count,
        COALESCE(l.leave_approved_days, 0) AS leave_approved_days
    FROM employees e
    LEFT JOIN ticket_usage t ON t.employee_id = e.employee_id
    LEFT JOIN leave_usage l ON l.employee_id = e.employee_id
    ORDER BY e.employee_id;
$$;

GRANT EXECUTE ON FUNCTION public.get_hr_employee_qualification_usage(text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_hr_employee_qualification_usage(text[]) TO anon;
