CREATE TABLE IF NOT EXISTS vendors (
    erp_vendor_id INTEGER PRIMARY KEY,
    vendor_name TEXT NOT NULL,
    salesman_name TEXT,
    salesman_contact TEXT,
    supervisor_name TEXT,
    supervisor_contact TEXT,
    vendor_contact_number TEXT,
    payment_method TEXT CHECK (payment_method IN ('Cash on Delivery', 'Bank on Delivery', 'Cash Credit', 'Bank Credit')),
    credit_period INTEGER,
    bank_name TEXT,
    iban TEXT,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Deactivated', 'Blacklisted')),
    last_visit TIMESTAMP,
    vendor_category TEXT DEFAULT 'Daily Fresh Vendor',
    warehouse_location TEXT,
    location_link TEXT,
    delivery_method TEXT CHECK (delivery_method IN ('Delivery Available', 'Pickup Only', 'Both Delivery and Pickup')),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);