<script lang="ts">
 import { onMount } from 'svelte';
 let users:any[]=[]; let loading=true; let error=''; let saving='';
 async function load(){loading=true;error='';const r=await fetch('/api/aqura-voice/admin');const j=await r.json();if(!r.ok)error=j.error;else users=(j.users||[]).map((u:any)=>({...u,aqura_voice:u.aqura_voice||{is_enabled:false,daily_limit:10,subscription_expiry:''}}));loading=false;}
 async function save(u:any){saving=u.id;error='';const a=u.aqura_voice||{};const r=await fetch('/api/aqura-voice/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:u.id,isEnabled:a.is_enabled===true,dailyLimit:a.daily_limit||10,subscriptionExpiry:a.subscription_expiry||null})});const j=await r.json();if(!r.ok)error=j.error;else await load();saving='';}
 onMount(load);
</script>
<div class="wrap"><header><div><h2>🎙️ Aqura Voice</h2><p>Master Admin controls for mobile-app access, subscription expiry and daily usage.</p></div><button on:click={load}>↻ Refresh</button></header>{#if error}<div class="error">{error}</div>{/if}{#if loading}<p>Loading…</p>{:else}<div class="table"><table><thead><tr><th>User</th><th>Employee / Branch</th><th>Access</th><th>Daily limit</th><th>Used today</th><th>Expiry</th><th>Action</th></tr></thead><tbody>{#each users as u}<tr><td><b>{u.username}</b>{#if u.is_master_admin}<small>Master Admin · Unlimited</small>{/if}</td><td>{u.employee_name||'—'}<small>{u.branch_name||'—'}</small></td><td>{#if u.is_master_admin}<span class="yes">Always enabled</span>{:else}<input type="checkbox" bind:checked={u.aqura_voice.is_enabled}/>{/if}</td><td>{#if u.is_master_admin}∞{:else}<input class="number" type="number" min="1" bind:value={u.aqura_voice.daily_limit}/>{/if}</td><td>{u.is_master_admin?'Unlimited':u.used_today}</td><td>{#if u.is_master_admin}Never{:else}<input type="date" bind:value={u.aqura_voice.subscription_expiry}/>{/if}</td><td>{#if !u.is_master_admin}<button class="save" disabled={saving===u.id} on:click={()=>save(u)}>{saving===u.id?'Saving…':'Save'}</button>{/if}</td></tr>{/each}</tbody></table></div>{/if}</div>
<style>.wrap{height:100%;overflow:auto;padding:20px;background:#f8fafc;color:#334155}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}h2{margin:0;color:#0b3c68}p{margin:5px 0;color:#64748b;font-size:12px}button{border:1px solid #06b6d4;background:#ecfeff;color:#0e7490;border-radius:7px;padding:7px 12px;font-weight:700;cursor:pointer}.table{background:white;border:1px solid #dbe4ee;border-radius:10px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#0b3c68;color:white;padding:10px}td{padding:10px;text-align:center;border-top:1px solid #e2e8f0}small{display:block;color:#64748b;margin-top:3px}.number,input[type=date]{max-width:130px;padding:6px;border:1px solid #cbd5e1;border-radius:6px}.save{background:#10b981;color:white;border-color:#10b981}.yes{color:#047857;font-weight:700}.error{padding:10px;background:#fee2e2;color:#b91c1c;border-radius:7px;margin-bottom:10px}</style>
