name: Check Recurring Schedules

# Run daily at 6:00 AM UTC (adjust timezone as needed)
on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-schedules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install @supabase/supabase-js dotenv
      
      - name: Run recurring schedule check
        env:
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node scripts/check-recurring-schedules.cjs
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Recurring schedule check failed!"
          echo "Please check the logs above for details"
